/- Modified for source distribution, 2026-09-10: unused declarations/imports
and development comments removed; retained mathematical statements unchanged. -/
import Init
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIBlockRadialPhysicalAngularFullSchwartzContinuation
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIBlockRadialPhysicalAngularFiniteAxis
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIDistributionalPartialTransform
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIBlockRadialSupremumBound



















noncomputable section

open Complex MeasureTheory Metric Set Topology
open scoped Classical

namespace OSReconstruction

variable {d k : Nat} [NeZero d] [NeZero k]
variable {rho : Real} {hrho : 0 < rho}
variable {center : Fin (k * (d + 1)) -> Real}
variable {hcenter : forall j : Fin k,
  rho <= center (finProdFinEquiv (j, (0 : Fin (d + 1))))}
variable {OS : OsterwalderSchraderAxioms d}
variable {lgc : OSLinearGrowthCondition d OS}
variable {Z : OSIIStep4SynchronizedMultiGapContinuationData d k hrho
  (osiiStep4MultiGapXiHatCenter d k center)
  (osiiStep4MultiGapXiHatCenter_time_lower d k center hcenter)}

namespace OSIIStep4FullSchwartzAngularContinuationData

/-- The OS-built full-imaginary slice distribution.  At imaginary
displacement `y`, evaluate the angular continuation at its physical target
logarithm and precompose with the normalized positive-basepoint lift from
reduced to absolute configurations. -/
noncomputable def imaginarySliceFamily
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc) :
    OSIIImaginarySliceDistributionFamily d k :=
  fun y =>
    (D.distribution
      (osiiStep4MultiGapTargetLog d k Z.uniform.T center y)).comp
      (BHW.reducedTestLift k d
          (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz)





def complexTargetDomain
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc) :
    Set (Fin (k * (d + 1)) -> Complex) :=
  osiiStep4MultiGapComplexTargetRightHalfPlane
      d k Z.uniform.T center ∩
    osiiStep4MultiGapComplexTargetLog d k Z.uniform.T center ⁻¹'
      D.carrier

/-- Evaluate the source-linear angular continuation at the complete complex
target generated by a displacement `z`. -/
noncomputable def complexTargetPairing
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc)
    (phi : SchwartzNPoint d k)
    (z : Fin (k * (d + 1)) -> Complex) : Complex :=
  D.distribution
      (osiiStep4MultiGapComplexTargetLog d k Z.uniform.T center z)
      (BHW.reducedTestLift k d
        (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz phi)

/-- For every fixed reduced source, the complete complex target pairing is
holomorphic on its natural displacement domain. -/
theorem complexTargetPairing_differentiableOn
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc)
    (phi : SchwartzNPoint d k) :
    DifferentiableOn Complex (D.complexTargetPairing phi)
      D.complexTargetDomain := by
  exact
    (D.weaklyHolomorphic
      (BHW.reducedTestLift k d
        (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz phi)).comp
      ((differentiableOn_osiiStep4MultiGapComplexTargetLog
        d k Z.uniform.T center).mono Set.inter_subset_left)
      (fun _z hz => hz.2)

/-- Real-edge covariance of the complete complex target pairing.  Translating
the reduced source by `a` and keeping displacement `x` is the same as keeping
the source fixed and replacing the displacement by `x - a`.  Both source
support hypotheses are explicit because first-carrier provenance is only
claimed on the equation-(6.6) localization carrier. -/
theorem complexTargetPairing_real_translate
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc)
    (phi : SchwartzNPoint d k)
    (a x : Fin (k * (d + 1)) -> Real)
    (hphi :
      Function.support (flattenSchwartzNPoint (d := d) phi) ⊆
        Metric.closedBall
          (osiiStep4MultiGapXiHatCenter d k center) (rho / 4))
    (hphi_translate :
      Function.support
          (flattenSchwartzNPoint (d := d)
            (translateSchwartzConfiguration
              (fun i mu => a (finProdFinEquiv (i, mu))) phi)) ⊆
        Metric.closedBall
          (osiiStep4MultiGapXiHatCenter d k center) (rho / 4))
    (hx : SCV.realToComplex x ∈
      osiiStep4MultiGapComplexTargetRightHalfPlane
        d k Z.uniform.T center)
    (hxa : SCV.realToComplex (x - a) ∈
      osiiStep4MultiGapComplexTargetRightHalfPlane
        d k Z.uniform.T center) :
    D.complexTargetPairing
        (translateSchwartzConfiguration
          (fun i mu => a (finProdFinEquiv (i, mu))) phi)
        (SCV.realToComplex x) =
      D.complexTargetPairing phi (SCV.realToComplex (x - a)) := by
  let rx : Fin k -> osiiAxisPairIndex d -> Real :=
    fun i b => Real.log
      (osiiStep4MultiGapComplexTargetCoeff d k Z.uniform.T center
        (SCV.realToComplex x) i b).re
  let rxa : Fin k -> osiiAxisPairIndex d -> Real :=
    fun i b => Real.log
      (osiiStep4MultiGapComplexTargetCoeff d k Z.uniform.T center
        (SCV.realToComplex (x - a)) i b).re
  have hlogx :
      osiiStep4MultiGapComplexTargetLog d k Z.uniform.T center
          (SCV.realToComplex x) =
        osiiAxisPairSimultaneousLogRealEmbed rx := by
    simpa [rx] using
      osiiStep4MultiGapComplexTargetLog_realToComplex_eq_realEmbed
        d k Z.uniform.T center x hx
  have hlogxa :
      osiiStep4MultiGapComplexTargetLog d k Z.uniform.T center
          (SCV.realToComplex (x - a)) =
        osiiAxisPairSimultaneousLogRealEmbed rxa := by
    simpa [rxa] using
      osiiStep4MultiGapComplexTargetLog_realToComplex_eq_realEmbed
        d k Z.uniform.T center (x - a) hxa
  rw [complexTargetPairing, hlogx,
    D.distribution_realEdge_reducedTestLift_eq_schwinger_translate_of_flatSupport
      rx
      (translateSchwartzConfiguration
        (fun i mu => a (finProdFinEquiv (i, mu))) phi)
      hphi_translate]
  rw [complexTargetPairing, hlogxa,
    D.distribution_realEdge_reducedTestLift_eq_schwinger_translate_of_flatSupport
      rxa phi hphi]
  apply congrArg (OS.S (k + 1))
  apply congrArg ZeroDiagonalSchwartz.ofClassical
  show
    translateSchwartzConfiguration
        (fun j => -osiiAxisPairChronologicalPointTranslation
          Z.coherent.T rx j)
        (BHW.reducedTestLift k d
          (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz
          (translateSchwartzConfiguration
            (fun i mu => a (finProdFinEquiv (i, mu))) phi)) =
      translateSchwartzConfiguration
        (fun j => -osiiAxisPairChronologicalPointTranslation
          Z.coherent.T rxa j)
        (BHW.reducedTestLift k d
          (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz phi)
  rw [Z.slope_eq]
  rw [translateConfiguration_reducedTestLift_axisPairGaps
      d k (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz
      (translateSchwartzConfiguration
        (fun i mu => a (finProdFinEquiv (i, mu))) phi)
      Z.uniform.T rx]
  rw [translateConfiguration_reducedTestLift_axisPairGaps
      d k (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz
      phi Z.uniform.T rxa]
  rw [translateSchwartzConfiguration_translateSchwartzConfiguration]
  apply congrArg
    (fun b : NPointDomain d k =>
      BHW.reducedTestLift k d
        (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz
        (translateSchwartzConfiguration b phi))
  have hgapx :=
    osiiStep4MultiGapXiHat_add_complexTargetRealLogTranslation
      d k Z.uniform.T (lt_trans zero_lt_one Z.uniform.hT).ne'
      center x hx
  have hgapxa :=
    osiiStep4MultiGapXiHat_add_complexTargetRealLogTranslation
      d k Z.uniform.T (lt_trans zero_lt_one Z.uniform.hT).ne'
      center (x - a) hxa
  ext i mu
  have hxcoord := congrFun hgapx (finProdFinEquiv (i, mu))
  have hxacoord := congrFun hgapxa (finProdFinEquiv (i, mu))
  simp only [Pi.add_apply,
    osiiStep4AxisPairGapTranslationFlat_finProdFinEquiv,
    Pi.sub_apply] at hxcoord hxacoord ⊢
  dsimp [rx, rxa] at hxcoord hxacoord ⊢
  linarith

/-- The real source-translation covariance extends across any connected
complex displacement window on which both target arguments stay in the
physical-angular continuation domain. -/
theorem complexTargetPairing_translate_eqOn
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc)
    (phi : SchwartzNPoint d k)
    (a : Fin (k * (d + 1)) -> Real)
    (hphi :
      Function.support (flattenSchwartzNPoint (d := d) phi) ⊆
        Metric.closedBall
          (osiiStep4MultiGapXiHatCenter d k center) (rho / 4))
    (hphi_translate :
      Function.support
          (flattenSchwartzNPoint (d := d)
            (translateSchwartzConfiguration
              (fun i mu => a (finProdFinEquiv (i, mu))) phi)) ⊆
        Metric.closedBall
          (osiiStep4MultiGapXiHatCenter d k center) (rho / 4))
    (U : Set (Fin (k * (d + 1)) -> Complex))
    (hU_open : IsOpen U)
    (hU_connected : IsConnected U)
    (x0 : Fin (k * (d + 1)) -> Real)
    (hx0 : SCV.realToComplex x0 ∈ U)
    (hU_domain : U ⊆ D.complexTargetDomain)
    (hU_shift : forall z, z ∈ U ->
      z - SCV.realEmbed a ∈ D.complexTargetDomain) :
    Set.EqOn
      (D.complexTargetPairing
        (translateSchwartzConfiguration
          (fun i mu => a (finProdFinEquiv (i, mu))) phi))
      (fun z => D.complexTargetPairing phi
        (z - SCV.realEmbed a)) U := by
  apply SCV.holomorphic_eq_of_eq_on_real_of_connected_finite
    hU_open hU_connected
  · exact
      (D.complexTargetPairing_differentiableOn
        (translateSchwartzConfiguration
          (fun i mu => a (finProdFinEquiv (i, mu))) phi)).mono
        hU_domain
  · exact
      (D.complexTargetPairing_differentiableOn phi).comp
        (differentiable_id.sub
          (differentiable_const (SCV.realEmbed a))).differentiableOn
        hU_shift
  · exact hx0
  · intro x hx
    have hreal_sub :
        SCV.realToComplex x - SCV.realEmbed a =
          SCV.realToComplex (x - a) := by
      ext i
      simp [SCV.realToComplex, SCV.realEmbed]
    change
      D.complexTargetPairing
          (translateSchwartzConfiguration
            (fun i mu => a (finProdFinEquiv (i, mu))) phi)
          (SCV.realToComplex x) =
        D.complexTargetPairing phi
          (SCV.realToComplex x - SCV.realEmbed a)
    rw [hreal_sub]
    have hxa : SCV.realToComplex (x - a) ∈
        osiiStep4MultiGapComplexTargetRightHalfPlane
          d k Z.uniform.T center := by
      rw [← hreal_sub]
      exact (hU_shift _ hx).1
    exact D.complexTargetPairing_real_translate phi a x
      hphi hphi_translate (hU_domain hx).1 hxa

/-- The zero imaginary slice has the direct Euclidean Schwinger value on the
support-local reduced-test class used by equation `(6.6)`.  This is the exact
real-edge normalization that any shifted holomorphic density must extend. -/
theorem imaginarySliceFamily_zero_apply_eq_schwinger_translate_of_flatSupport
    (D : OSIIStep4FullSchwartzAngularContinuationData
      (hcenter := hcenter) Z OS lgc)
    (phi : SchwartzNPoint d k)
    (hsupport :
      Function.support (flattenSchwartzNPoint (d := d) phi) ⊆
        Metric.closedBall
          (osiiStep4MultiGapXiHatCenter d k center) (rho / 4)) :
    D.imaginarySliceFamily 0 phi =
      OS.S (k + 1) (ZeroDiagonalSchwartz.ofClassical
        (translateSchwartzConfiguration
          (fun i =>
            -osiiAxisPairChronologicalPointTranslation Z.coherent.T
              (fun j a => Real.log
                (osiiStep4MultiGapTargetCoeff
                  d k Z.uniform.T center 0 j a).re)
              i)
          (BHW.reducedTestLift k d
            (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz phi))) := by
  have hcenterPos : forall i : Fin k,
      0 < center (finProdFinEquiv (i, (0 : Fin (d + 1)))) :=
    fun i => hrho.trans_le (hcenter i)
  change
    D.distribution
        (osiiStep4MultiGapTargetLog d k Z.uniform.T center 0)
        (BHW.reducedTestLift k d
          (osiiStep4PositiveTimeBasepointCutoff d).toSchwartz phi) = _
  rw [osiiStep4MultiGapTargetLog_zero_eq_realEmbed
    d k Z.uniform.T (lt_trans zero_lt_one Z.uniform.hT)
      center hcenterPos]
  exact
    D.distribution_realEdge_reducedTestLift_eq_schwinger_translate_of_flatSupport
      (fun j a => Real.log
        (osiiStep4MultiGapTargetCoeff
          d k Z.uniform.T center 0 j a).re)
      phi hsupport

end OSIIStep4FullSchwartzAngularContinuationData

namespace OSIIStep4SynchronizedMultiGapContinuationData

variable (Z : OSIIStep4SynchronizedMultiGapContinuationData d k hrho
  (osiiStep4MultiGapXiHatCenter d k center)
  (osiiStep4MultiGapXiHatCenter_time_lower d k center hcenter))

/-- Correct compact angular target family for equation `(6.6)`.  The target
logarithm depends only on the observed imaginary variable `y`; that variable
ranges over the `rho / 4` projection of the partial-convolution support. -/
def physicalAngularEquation66MaskedTargetSet
    (A : Finset (osiiAxisPairIndex d)) :
    Set (Fin k -> osiiAxisPairIndex d -> Complex) :=
  (fun y : Fin (k * (d + 1)) -> Real =>
    Z.physicalAngularMaskedTargetLog (hcenter := hcenter) A
      (fun a => (y a : Complex))) ''
    Metric.closedBall 0 (rho / 4)

end OSIIStep4SynchronizedMultiGapContinuationData

/-- A source-linear angular continuation covering one finite signed-axis mask
on the exact `(6.6)` target family. -/
structure OSIIStep4FullSchwartzAngularEquation66FinsetCoveredData
    (Z : OSIIStep4SynchronizedMultiGapContinuationData d k hrho
      (osiiStep4MultiGapXiHatCenter d k center)
      (osiiStep4MultiGapXiHatCenter_time_lower d k center hcenter))
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSLinearGrowthCondition d OS)
    (A : Finset (osiiAxisPairIndex d)) where
  continuationData : OSIIStep4FullSchwartzAngularContinuationData
    (hcenter := hcenter) Z OS lgc
  coverage :
    Z.physicalAngularEquation66MaskedTargetSet
        (hcenter := hcenter) A ⊆
      continuationData.carrier

namespace OSIIStep4FullSchwartzAngularEquation66FinsetSuccessorData

variable {Z : OSIIStep4SynchronizedMultiGapContinuationData d k hrho
  (osiiStep4MultiGapXiHatCenter d k center)
  (osiiStep4MultiGapXiHatCenter_time_lower d k center hcenter)}
variable {A : Finset (osiiAxisPairIndex d)}
variable {C : OSIIStep4FullSchwartzAngularEquation66FinsetCoveredData
  (hcenter := hcenter) Z OS lgc A}
variable {a : osiiAxisPairIndex d}

end OSIIStep4FullSchwartzAngularEquation66FinsetSuccessorData

namespace OSIIStep4FullSchwartzAngularExtensionAtlasData

variable {Z : OSIIStep4SynchronizedMultiGapContinuationData d k hrho
  (osiiStep4MultiGapXiHatCenter d k center)
  (osiiStep4MultiGapXiHatCenter_time_lower d k center hcenter)}
variable {A : Finset (osiiAxisPairIndex d)}
variable {C : OSIIStep4FullSchwartzAngularEquation66FinsetCoveredData
  (hcenter := hcenter) Z OS lgc A}
variable {index : Type*}

end OSIIStep4FullSchwartzAngularExtensionAtlasData

namespace OSIIStep4SynchronizedMultiGapContinuationData

variable (Z : OSIIStep4SynchronizedMultiGapContinuationData d k hrho
  (osiiStep4MultiGapXiHatCenter d k center)
  (osiiStep4MultiGapXiHatCenter_time_lower d k center hcenter))

end OSIIStep4SynchronizedMultiGapContinuationData
end OSReconstruction
