import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIEuclideanHolomorphicGluing
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIEuclideanWardSource

/-!
# Mixed spacelike points in the native holomorphic domain

A skew rotation generated by the spatial part of the selected real gap
has a strictly future-timelike imaginary tangent precisely when that gap
is spacelike. Small positive rotations enter the physical tube; openness
keeps every other, already interior, gap there. This is pure geometry and
does not assume any reconstructed Wightman axiom.
-/

noncomputable section

open Complex Filter Set Topology
open scoped Classical Matrix.Norms.Operator

set_option backward.isDefEq.respectTransparency false

namespace OSReconstruction

variable {d k : Nat} [NeZero d]

def osiiWickConjugatedMatrix
    (R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (z : Fin (d + 1) -> Complex) : Fin (d + 1) -> Complex :=
  osiiAxisPairWickBlockCLE
    ((R.map Complex.ofReal).mulVec ((osiiAxisPairWickBlockCLE (d := d)).symm z))

private theorem wickConjugatedMatrix_im
    (R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (z : Fin (d + 1) -> Complex) (mu : Fin (d + 1)) :
    (osiiWickConjugatedMatrix R z mu).im =
      if mu = 0 then
        R.mulVec (fun nu => ((osiiAxisPairWickBlockCLE (d := d)).symm z nu).re) mu
      else R.mulVec (fun nu => ((osiiAxisPairWickBlockCLE (d := d)).symm z nu).im) mu := by
  refine Fin.cases ?_ (fun a => ?_) mu
  ·
    simp [osiiWickConjugatedMatrix, osiiAxisPairWickBlock, Matrix.mulVec, dotProduct]
  · simp [osiiWickConjugatedMatrix, osiiAxisPairWickBlock, Matrix.mulVec, dotProduct]

@[simp] theorem osiiWickConjugatedMatrix_one (z : Fin (d + 1) -> Complex) :
    osiiWickConjugatedMatrix 1 z = z := by
  simp [osiiWickConjugatedMatrix]

private theorem hasDerivAt_wickConjugatedMatrix_im
    (Y : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (z : Fin (d + 1) -> Complex) :
    HasDerivAt
      (fun t : Real => fun mu => (osiiWickConjugatedMatrix (NormedSpace.exp (t • Y)) z mu).im)
      (fun mu => (osiiWickConjugatedMatrix Y z mu).im) 0 := by
  have hmat : HasDerivAt (fun t : Real => NormedSpace.exp (t • Y)) Y 0 := by
    simpa using hasDerivAt_exp_smul_const Y (0 : Real)
  have hentry (mu nu : Fin (d + 1)) :
      HasDerivAt (fun t : Real => NormedSpace.exp (t • Y) mu nu) (Y mu nu) 0 := by
    let ev : Matrix (Fin (d + 1)) (Fin (d + 1)) Real →L[Real] Real :=
      ((LinearMap.proj nu : (Fin (d + 1) -> Real) →ₗ[Real] Real).comp
        (LinearMap.proj mu)).toContinuousLinearMap
    exact ev.hasFDerivAt.comp_hasDerivAt 0 hmat
  apply hasDerivAt_pi.mpr
  intro mu
  simp only [wickConjugatedMatrix_im]
  split_ifs <;> simp only [Matrix.mulVec, dotProduct]
  all_goals
    apply HasDerivAt.fun_sum
    intro nu _
    exact (hentry mu nu).mul_const _

private def spacelikeRotationGenerator (v : Fin (d + 1) -> Real) :
    Matrix (Fin (d + 1)) (Fin (d + 1)) Real :=
  fun mu nu => if mu = 0 then (if nu = 0 then 0 else v nu)
    else if nu = 0 then -v mu else 0

omit [NeZero d] in
private theorem spacelikeRotationGenerator_skew (v : Fin (d + 1) -> Real) :
    (spacelikeRotationGenerator v).transpose = -spacelikeRotationGenerator v := by
  ext mu nu
  by_cases hmu : mu = 0 <;> by_cases hnu : nu = 0 <;>
    simp [spacelikeRotationGenerator, Matrix.transpose_apply, hmu, hnu]

private theorem spacelikeRotationGenerator_im (v : Fin (d + 1) -> Real) :
    (fun mu => (osiiWickConjugatedMatrix (spacelikeRotationGenerator v)
      (fun nu => (v nu : Complex)) mu).im) =
      Fin.cases (∑ a : Fin d, v a.succ ^ 2) (fun a => v 0 * v a.succ) := by
  ext mu
  rw [wickConjugatedMatrix_im]
  refine Fin.cases ?_ (fun a => ?_) mu
  · simp [Matrix.mulVec, dotProduct, Fin.sum_univ_succ, spacelikeRotationGenerator,
      osiiAxisPairInverseWickBlock, pow_two]
  · simp [Matrix.mulVec, dotProduct, spacelikeRotationGenerator,
      osiiAxisPairInverseWickBlock, mul_comm]

private theorem spacelikeRotationGenerator_future
    (v : Fin (d + 1) -> Real) (hv : MinkowskiSpace.IsSpacelike d v) :
    InOpenForwardCone d (fun mu => (osiiWickConjugatedMatrix
      (spacelikeRotationGenerator v) (fun nu => (v nu : Complex)) mu).im) := by
  rw [spacelikeRotationGenerator_im]
  have hv' : v 0 ^ 2 < ∑ a : Fin d, v a.succ ^ 2 := by
    simpa [MinkowskiSpace.IsSpacelike, MinkowskiSpace.minkowskiNormSq_eq,
      MinkowskiSpace.timeComponent, MinkowskiSpace.spatialComponents] using hv
  have hpos : 0 < ∑ a : Fin d, v a.succ ^ 2 := lt_of_le_of_lt (sq_nonneg _) hv'
  refine ⟨hpos, ?_⟩
  rw [MinkowskiSpace.minkowskiNormSq_eq]
  simp only [MinkowskiSpace.timeComponent, MinkowskiSpace.spatialComponents,
    Fin.cases_zero, Fin.cases_succ, mul_pow, ← Finset.mul_sum]
  nlinarith [mul_lt_mul_of_pos_right hv' hpos]

private theorem isOpen_forwardCone : IsOpen {v | InOpenForwardCone d v} := by
  have hq : Continuous (MinkowskiSpace.minkowskiNormSq d) := by
    have h : Continuous (fun v : Fin (d + 1) -> Real =>
        -(v 0)^2 + ∑ a : Fin d, (v a.succ)^2) := by fun_prop
    convert h using 1
    ext v
    exact MinkowskiSpace.minkowskiNormSq_eq d v
  exact (isOpen_lt continuous_const (continuous_apply 0)).inter
    (isOpen_lt hq continuous_const)

private theorem eventually_forward_of_deriv
    {f : Real -> Fin (d + 1) -> Real} {v : Fin (d + 1) -> Real}
    (hf : HasDerivAt f v 0) (hzero : f 0 = 0) (hv : InOpenForwardCone d v) :
    ∀ᶠ t in 𝓝[>] (0 : Real), InOpenForwardCone d (f t) := by
  have hlim := hf.tendsto_slope_zero_right
  simp only [zero_add, hzero, sub_zero] at hlim
  filter_upwards [hlim.eventually (isOpen_forwardCone.mem_nhds hv),
    self_mem_nhdsWithin] with t ht hpos
  have htpos : 0 < t := hpos
  have h := inOpenForwardCone_smul d t htpos _ ht
  simpa [smul_smul, ne_of_gt htpos] using h

theorem exists_osiiWickRotation_mixedSpacelike
    (xi : Fin k -> Fin (d + 1) -> Complex) (j : Fin k)
    (hj : MinkowskiSpace.IsSpacelike d (fun mu => (xi j mu).re))
    (him : ∀ mu, (xi j mu).im = 0)
    (hother : ∀ l, l ≠ j -> InOpenForwardCone d (fun mu => (xi l mu).im)) :
    ∃ R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real,
      (R.transpose * R = 1 ∧ R.det = 1) ∧
      ∀ l, InOpenForwardCone d (fun mu => (osiiWickConjugatedMatrix R (xi l) mu).im) := by
  let v : Fin (d + 1) -> Real := fun mu => (xi j mu).re
  let Y := spacelikeRotationGenerator v
  have hx : xi j = fun mu => (v mu : Complex) := by
    ext mu
    exact Complex.ext rfl (him mu)
  have hevent : ∀ᶠ t in 𝓝[>] (0 : Real),
      ∀ l, InOpenForwardCone d
        (fun mu => (osiiWickConjugatedMatrix (NormedSpace.exp (t • Y)) (xi l) mu).im) := by
    apply Filter.eventually_all.mpr
    intro l
    by_cases hl : l = j
    · subst l
      apply eventually_forward_of_deriv (hasDerivAt_wickConjugatedMatrix_im Y (xi j))
      · ext mu
        simpa using him mu
      · rw [hx]
        exact spacelikeRotationGenerator_future v hj
    · have hzero : InOpenForwardCone d
          (fun mu => (osiiWickConjugatedMatrix (NormedSpace.exp ((0 : Real) • Y)) (xi l) mu).im) := by
        simpa using hother l hl
      exact ((hasDerivAt_wickConjugatedMatrix_im Y (xi l)).continuousAt.eventually
        (isOpen_forwardCone.mem_nhds hzero)).filter_mono nhdsWithin_le_nhds
  obtain ⟨t, ht⟩ := hevent.exists
  exact ⟨NormedSpace.exp (t • Y),
    ⟨osiiEuclidean_exp_skew_orthogonal Y (spacelikeRotationGenerator_skew v) t,
      osiiEuclidean_exp_skew_det_one Y (spacelikeRotationGenerator_skew v) t⟩, ht⟩

theorem osiiEuclideanOrderComplexTubeMap_inverseWick_refl
    (R : {R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real // R.transpose * R = 1 ∧ R.det = 1})
    (z : Fin (k + 1) -> Fin (d + 1) -> Complex) :
    osiiEuclideanOrderComplexTubeMap (R, Equiv.refl _)
        (fun j => (osiiAxisPairWickBlockCLE (d := d)).symm (z j)) =
      fun j => osiiWickConjugatedMatrix R.val (BHW.reducedDiffMap (k + 1) d z j) := by
  ext j mu
  rw [osiiEuclideanOrderComplexTubeMap_apply, ← osiiAxisPairWickBlockCLE_apply]
  change (osiiAxisPairWickBlockCLE
      ((R.val.map Complex.ofReal).mulVec ((osiiAxisPairWickBlockCLE (d := d)).symm (z j.succ)) -
       (R.val.map Complex.ofReal).mulVec ((osiiAxisPairWickBlockCLE (d := d)).symm (z j.castSucc)))) mu =
    (osiiAxisPairWickBlockCLE ((R.val.map Complex.ofReal).mulVec
      ((osiiAxisPairWickBlockCLE (d := d)).symm (z j.succ - z j.castSucc)))) mu
  simp only [map_sub, Matrix.mulVec_sub]

theorem osiiEuclideanHolomorphicDomain_of_mixedSpacelike
    {z : Fin (k + 1) -> Fin (d + 1) -> Complex} (j : Fin k)
    (hj : MinkowskiSpace.IsSpacelike d
      (fun mu => (BHW.reducedDiffMap (k + 1) d z j mu).re))
    (him : ∀ mu, (BHW.reducedDiffMap (k + 1) d z j mu).im = 0)
    (hother : ∀ l, l ≠ j -> InOpenForwardCone d
      (fun mu => (BHW.reducedDiffMap (k + 1) d z l mu).im)) :
    z ∈ osiiEuclideanHolomorphicDomain d k := by
  obtain ⟨R, hR, hxi⟩ := exists_osiiWickRotation_mixedSpacelike
    (BHW.reducedDiffMap (k + 1) d z) j hj him hother
  refine Set.mem_iUnion.mpr ⟨(⟨R, hR⟩, Equiv.refl _), ?_⟩
  change osiiEuclideanOrderComplexTubeMap (⟨R, hR⟩, Equiv.refl _)
    (fun a => (osiiAxisPairWickBlockCLE (d := d)).symm (z a)) ∈
      TubeDomainSetPi (BHW.ProductForwardConeReal d k)
  rw [osiiEuclideanOrderComplexTubeMap_inverseWick_refl]
  intro l
  exact (inOpenForwardCone_iff _).mpr (hxi l)

end OSReconstruction
