import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVLowerAnchoredPacket
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVTargetHubReflectedGramReplacement
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVVacuumTailPredecessorMatch

/-!
# Target-and-hub convex charts for the vacuum-tail branch

A target-and-hub adapted universal atlas controls the complete compact
parameter box generated by the centered positive-real hub and one centered
mixed target.  The box also contains the origin, so an open convex thickening
inside the source-linear domain simultaneously retains:

* the packet anchor, needed for the local predecessor comparison;
* the fixed predecessor hub, needed for pointed-atlas propagation; and
* the exact absolute mixed target.

This is the fixed-anchor replacement for the earlier vanishing-anchor route.
-/

noncomputable section

open Complex Set Topology
open scoped Classical

namespace OSReconstruction
namespace OSIIChapterV

variable {d q : ℕ} [NeZero d]
variable
  {L : SimultaneousTimeContinuationStageLevel d}
  {OS : OsterwalderSchraderAxioms d}
  {K : Set (Fin ((q + 1) + 1) → ℝ)}
  {sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ}
  {z : Fin (q + 1) → ℂ}

namespace UniversalCompactCarrierAnchoredAtlasData

open Section43ProductTimeApproximateIdentity
open Section43ProductTimeApproximateIdentity.AnchoredPacketTimeShellFamilyData

variable
  {I : Section43ProductTimeApproximateIdentity (q + 1)}
  {anchor : Fin (q + 1) → ℝ}
  {A : AnchoredPacketTimeShellFamilyData (d := d) I anchor}

/-- Reinterpret a universal atlas over the explicit fixed-head carrier as the
packet-specialized atlas used by the vacuum-tail construction. -/
noncomputable def toPositiveHead
    (D :
      UniversalCompactCarrierAnchoredAtlasData
        L OS A.positiveHeadSpatialSourceCarrier) :
    PositiveHeadUniversalAnchoredAtlasData L OS A where
  sourceStage := D.sourceStage
  sourceStage_eq := D.sourceStage_eq
  gram := D.gram

@[simp]
theorem toPositiveHead_spatialLinearDomain
    (D :
      UniversalCompactCarrierAnchoredAtlasData
        L OS A.positiveHeadSpatialSourceCarrier) :
    D.toPositiveHead.spatialLinearDomain =
      D.spatialLinearDomain :=
  rfl

end UniversalCompactCarrierAnchoredAtlasData

/-- The compact centered parameter box controlled by a target-and-hub
adapted atlas. -/
def vacuumTailTargetHubBox
    (sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ)
    (z : Fin (q + 1) → ℂ) :
    Set (Fin (q + 1) → ℂ) :=
  (fun p : ℝ × ℝ =>
    tailAnchorTargetHubBoxPoint
      sourceAnchor sourceHub z p.1 p.2) ''
    (Set.Icc (0 : ℝ) 1 ×ˢ Set.Icc (0 : ℝ) 1)

theorem vacuumTailTargetHubBox_compact
    (sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ)
    (z : Fin (q + 1) → ℂ) :
    IsCompact (vacuumTailTargetHubBox sourceAnchor sourceHub z) := by
  have hcontinuous :
      Continuous
        (fun p : ℝ × ℝ =>
          tailAnchorTargetHubBoxPoint
            sourceAnchor sourceHub z p.1 p.2) := by
    apply continuous_pi
    intro i
    simpa [tailAnchorTargetHubBoxPoint_apply] using
      (((Complex.continuous_ofReal.comp continuous_fst).mul
          continuous_const).add
        ((Complex.continuous_ofReal.comp continuous_snd).mul
          continuous_const))
  exact
    (isCompact_Icc.prod isCompact_Icc).image hcontinuous

theorem vacuumTailTargetHubBox_convex
    (sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ)
    (z : Fin (q + 1) → ℂ) :
    Convex ℝ (vacuumTailTargetHubBox sourceAnchor sourceHub z) := by
  rintro x ⟨p, hp, rfl⟩ y ⟨r, hr, rfl⟩ a b ha hb hab
  let s : ℝ × ℝ := a • p + b • r
  have hs :
      s ∈ Set.Icc (0 : ℝ) 1 ×ˢ Set.Icc (0 : ℝ) 1 := by
    exact
      ((convex_Icc (0 : ℝ) 1).prod
        (convex_Icc (0 : ℝ) 1)) hp hr ha hb hab
  refine ⟨s, hs, ?_⟩
  change
    (a * p.1 + b * r.1) •
          tailAnchorCenteredHubPoint sourceAnchor sourceHub +
        (a * p.2 + b * r.2) •
          tailAnchorCenteredPoint sourceAnchor z =
      a •
          (p.1 • tailAnchorCenteredHubPoint sourceAnchor sourceHub +
            p.2 • tailAnchorCenteredPoint sourceAnchor z) +
        b •
          (r.1 • tailAnchorCenteredHubPoint sourceAnchor sourceHub +
            r.2 • tailAnchorCenteredPoint sourceAnchor z)
  module

theorem zero_mem_vacuumTailTargetHubBox
    (sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ)
    (z : Fin (q + 1) → ℂ) :
    0 ∈ vacuumTailTargetHubBox sourceAnchor sourceHub z := by
  refine ⟨(0, 0), ?_, ?_⟩
  · simp
  · ext i
    simp [tailAnchorTargetHubBoxPoint_apply]

theorem centeredHub_mem_vacuumTailTargetHubBox
    (sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ)
    (z : Fin (q + 1) → ℂ) :
    tailAnchorCenteredHubPoint sourceAnchor sourceHub ∈
      vacuumTailTargetHubBox sourceAnchor sourceHub z := by
  refine ⟨(1, 0), ?_, ?_⟩
  · simp
  · ext i
    simp [tailAnchorTargetHubBoxPoint_apply,
      tailAnchorCenteredHubPoint_apply]

theorem centeredTarget_mem_vacuumTailTargetHubBox
    (sourceAnchor sourceHub : Fin ((q + 1) + 1) → ℝ)
    (z : Fin (q + 1) → ℂ) :
    tailAnchorCenteredPoint sourceAnchor z ∈
      vacuumTailTargetHubBox sourceAnchor sourceHub z := by
  refine ⟨(0, 1), ?_, ?_⟩
  · simp
  · ext i
    simp [tailAnchorTargetHubBoxPoint_apply,
      tailAnchorCenteredPoint]

/-- An open convex centered chart containing the origin, the centered hub,
and the centered target inside one target-and-hub adapted source-linear
domain. -/
structure VacuumTailTargetHubCenteredConvexChartData
    (D :
      TargetHubAdaptedUniversalCompactCarrierAnchoredAtlasData
        L OS K sourceAnchor sourceHub z) where
  domain : Set (Fin (q + 1) → ℂ)
  domain_open : IsOpen domain
  domain_convex : Convex ℝ domain
  zero_mem : 0 ∈ domain
  hub_mem : tailAnchorCenteredHubPoint sourceAnchor sourceHub ∈ domain
  target_mem : tailAnchorCenteredPoint sourceAnchor z ∈ domain
  domain_subset : domain ⊆ D.atlas.spatialLinearDomain
  domain_subset_reachableAtlas :
    domain ⊆ D.atlas.gram.reachableAnchoredAtlasCoveredDomain
      D.atlas.sourceStage.stage D.atlas.sourceStage.germ

/-- The controlled compact parameter box admits an open convex thickening
inside the selected source-linear atlas domain. -/
theorem nonempty_vacuumTailTargetHubCenteredConvexChartData
    (D :
      TargetHubAdaptedUniversalCompactCarrierAnchoredAtlasData
        L OS K sourceAnchor sourceHub z) :
    Nonempty (VacuumTailTargetHubCenteredConvexChartData D) := by
  let quantitativeDomain : Set (Fin (q + 1) → ℂ) :=
    D.atlas.spatialLinearDomain ∩
      D.atlas.gram.reachableAnchoredAtlasCoveredDomain
        D.atlas.sourceStage.stage D.atlas.sourceStage.germ
  have hquantitative_open : IsOpen quantitativeDomain :=
    D.atlas.spatialLinearDomain_open.inter
      (D.atlas.gram.reachableAnchoredAtlasCoveredDomain_open
        D.atlas.sourceStage.stage D.atlas.sourceStage.germ)
  have hbox_subset :
      vacuumTailTargetHubBox sourceAnchor sourceHub z ⊆
        quantitativeDomain := by
    rintro _ ⟨p, hp, rfl⟩
    exact ⟨D.boxPoint_mem_spatialLinearDomain hp.1 hp.2,
      D.boxPoint_mem_reachableAnchoredAtlasCoveredDomain hp.1 hp.2⟩
  obtain ⟨r, hr, hthick⟩ :=
    (vacuumTailTargetHubBox_compact sourceAnchor sourceHub z
      ).exists_thickening_subset_open
        hquantitative_open hbox_subset
  exact
    ⟨{
      domain :=
        Metric.thickening r
          (vacuumTailTargetHubBox sourceAnchor sourceHub z)
      domain_open := Metric.isOpen_thickening
      domain_convex :=
        (vacuumTailTargetHubBox_convex sourceAnchor sourceHub z
          ).thickening r
      zero_mem :=
        Metric.self_subset_thickening hr _
          (zero_mem_vacuumTailTargetHubBox
            sourceAnchor sourceHub z)
      hub_mem :=
        Metric.self_subset_thickening hr _
          (centeredHub_mem_vacuumTailTargetHubBox
            sourceAnchor sourceHub z)
      target_mem :=
        Metric.self_subset_thickening hr _
          (centeredTarget_mem_vacuumTailTargetHubBox
            sourceAnchor sourceHub z)
      domain_subset := fun _ h => (hthick h).1
      domain_subset_reachableAtlas := fun _ h => (hthick h).2 }⟩

/-- Select the centered target-and-hub chart. -/
noncomputable def selectedVacuumTailTargetHubCenteredConvexChartData
    (D :
      TargetHubAdaptedUniversalCompactCarrierAnchoredAtlasData
        L OS K sourceAnchor sourceHub z) :
    VacuumTailTargetHubCenteredConvexChartData D :=
  Classical.choice
    (nonempty_vacuumTailTargetHubCenteredConvexChartData D)

end OSIIChapterV
end OSReconstruction
