/- Modified for source distribution, 2026-09-10: unused declarations/imports
and development comments removed; retained mathematical statements unchanged. -/
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVTargetAdaptedMovingSliceCoverage















noncomputable section

open Complex Set Topology
open scoped Classical

namespace OSReconstruction
namespace OSIIChapterV

/-- The analytic tail of a positive-real hub after subtracting the source
anchor tail. -/
def tailAnchorCenteredHubPoint
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ) :
    Fin m → ℂ :=
  tailAnchorCenteredPoint anchor (fun i => (hub i.succ : ℂ))

@[simp]
theorem tailAnchorCenteredHubPoint_sub_const
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (delta : ℝ) :
    tailAnchorCenteredHubPoint
        (fun i => anchor i - delta)
        (fun i => hub i - delta) =
      tailAnchorCenteredHubPoint anchor hub := by
  ext i
  simp [tailAnchorCenteredHubPoint, tailAnchorCenteredPoint]

/-- The two-parameter box generated by the centered positive-real hub and
the centered mixed target. -/
def tailAnchorTargetHubBoxPoint
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ)
    (u v : ℝ) :
    Fin m → ℂ :=
  u • tailAnchorCenteredHubPoint anchor hub +
    v • tailAnchorCenteredPoint anchor z

@[simp]
theorem tailAnchorCenteredHubPoint_apply
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (i : Fin m) :
    tailAnchorCenteredHubPoint anchor hub i =
      hub i.succ - anchor i.succ := by
  simp [tailAnchorCenteredHubPoint, tailAnchorCenteredPoint]

@[simp]
theorem tailAnchorTargetHubBoxPoint_apply
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ)
    (u v : ℝ)
    (i : Fin m) :
    tailAnchorTargetHubBoxPoint anchor hub z u v i =
      (u : ℂ) * (hub i.succ - anchor i.succ) +
        (v : ℂ) * (z i - anchor i.succ) := by
  simp [tailAnchorTargetHubBoxPoint, tailAnchorCenteredPoint,
    tailAnchorCenteredHubPoint, Complex.real_smul]

@[simp]
theorem reflectedCauchyShiftedStagePoint_targetHubBox_left
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (τ : Fin (m + (m + 1)) → ℝ)
    (z : Fin m → ℂ)
    (u v : ℝ)
    (i : Fin m) :
    reflectedCauchyShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v)
        (Fin.castAdd (m + 1) i) =
      reflectedCauchyShiftedStagePoint τ
          (v • tailAnchorCenteredPoint anchor z)
          (Fin.castAdd (m + 1) i) +
        u * (hub (Fin.rev i).succ - anchor (Fin.rev i).succ) := by
  rw [reflectedCauchyShiftedStagePoint_left,
    reflectedCauchyShiftedStagePoint_left]
  simp only [tailAnchorTargetHubBoxPoint_apply, Pi.smul_apply,
    Complex.real_smul, tailAnchorCenteredPoint, map_add, map_mul,
    map_sub, Complex.conj_ofReal]
  ring

@[simp]
theorem reflectedCauchyShiftedStagePoint_targetHubBox_bridge
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (τ : Fin (m + (m + 1)) → ℝ)
    (z : Fin m → ℂ)
    (u v : ℝ) :
    reflectedCauchyShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v)
        (Fin.natAdd m (0 : Fin (m + 1))) =
      τ (Fin.natAdd m (0 : Fin (m + 1))) := by
  exact reflectedCauchyShiftedStagePoint_bridge τ _

@[simp]
theorem reflectedCauchyShiftedStagePoint_targetHubBox_right
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (τ : Fin (m + (m + 1)) → ℝ)
    (z : Fin m → ℂ)
    (u v : ℝ)
    (i : Fin m) :
    reflectedCauchyShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v)
        (Fin.natAdd m i.succ) =
      reflectedCauchyShiftedStagePoint τ
          (v • tailAnchorCenteredPoint anchor z)
          (Fin.natAdd m i.succ) +
        u * (hub i.succ - anchor i.succ) := by
  rw [reflectedCauchyShiftedStagePoint_right,
    reflectedCauchyShiftedStagePoint_right]
  simp only [tailAnchorTargetHubBoxPoint_apply, Pi.smul_apply,
    Complex.real_smul, tailAnchorCenteredPoint]
  ring

@[simp]
theorem zeroAnchorShiftedStagePoint_targetHubBox_right
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (τ : Fin (m + (m + 1)) → ℝ)
    (z : Fin m → ℂ)
    (u v : ℝ)
    (i : Fin m) :
    zeroAnchorShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v)
        (Fin.natAdd m i.succ) =
      zeroAnchorShiftedStagePoint τ
          (v • tailAnchorCenteredPoint anchor z)
          (Fin.natAdd m i.succ) +
        u * (hub i.succ - anchor i.succ) := by
  rw [zeroAnchorShiftedStagePoint_right,
    zeroAnchorShiftedStagePoint_right]
  simp only [tailAnchorTargetHubBoxPoint_apply, Pi.smul_apply,
    Complex.real_smul, tailAnchorCenteredPoint]
  ring

private theorem targetHub_real_shift_nonnegative
    {a h u : ℝ}
    (hah : a ≤ h)
    (hu : u ∈ Set.Icc (0 : ℝ) 1) :
    0 ≤ u * (h - a) :=
  mul_nonneg hu.1 (sub_nonneg.mpr hah)

/-- Every reflected Cauchy scalar-stage point over the target-and-hub box
remains in the product right half-plane. -/
theorem
    reflectedCauchyShiftedStagePoint_targetHubBox_mem_rightHalfPlane
    {m : ℕ}
    {anchor hub : Fin (m + 1) → ℝ}
    {τ : Fin (m + (m + 1)) → ℝ}
    {z : Fin m → ℂ}
    {u v : ℝ}
    (hanchor :
      anchor ∈ section43TimeStrictPositiveRegion (m + 1))
    (hhub : ∀ i, anchor i ≤ hub i)
    (hτ : ReflectedTimeDominatesTailAnchor anchor τ)
    (hz : z ∈ osiiTimeRightHalfPlane m)
    (hu : u ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Icc (0 : ℝ) 1) :
    reflectedCauchyShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
      osiiTimeRightHalfPlane (m + (m + 1)) := by
  have hbase :=
    reflectedCauchyShiftedStagePoint_tailAnchorCentered_mem_rightHalfPlane
      hanchor hτ hz hv
  intro j
  refine Fin.addCases ?_ ?_ j
  · intro i
    rw [reflectedCauchyShiftedStagePoint_targetHubBox_left]
    have hshift :
        0 ≤ u * (hub (Fin.rev i).succ - anchor (Fin.rev i).succ) :=
      targetHub_real_shift_nonnegative
        (hhub (Fin.rev i).succ) hu
    simpa using
      add_pos_of_pos_of_nonneg
        (hbase (Fin.castAdd (m + 1) i)) hshift
  · intro r
    refine Fin.cases ?_ (fun i => ?_) r
    · rw [reflectedCauchyShiftedStagePoint_targetHubBox_bridge]
      exact hτ.2.1
    · rw [reflectedCauchyShiftedStagePoint_targetHubBox_right]
      have hshift :
          0 ≤ u * (hub i.succ - anchor i.succ) :=
        targetHub_real_shift_nonnegative (hhub i.succ) hu
      simpa using
        add_pos_of_pos_of_nonneg
          (hbase (Fin.natAdd m i.succ)) hshift

/-- Adding the centered positive-real hub does not enlarge any reflected
Cauchy principal argument beyond the original mixed target diagonal. -/
theorem
    abs_argumentVector_reflectedCauchyShiftedStagePoint_targetHubBox_le
    {m : ℕ}
    {anchor hub : Fin (m + 1) → ℝ}
    {τ : Fin (m + (m + 1)) → ℝ}
    {z : Fin m → ℂ}
    {u v : ℝ}
    (hanchor :
      anchor ∈ section43TimeStrictPositiveRegion (m + 1))
    (hhub : ∀ i, anchor i ≤ hub i)
    (hτ : ReflectedTimeDominatesTailAnchor anchor τ)
    (hz : z ∈ osiiTimeRightHalfPlane m)
    (hu : u ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Icc (0 : ℝ) 1) :
    ∀ j,
      |osiiTimeArgumentVector
          (reflectedCauchyShiftedStagePoint τ
            (tailAnchorTargetHubBoxPoint anchor hub z u v)) j| ≤
        |reflectedMixedDiagonal z j| := by
  have hbase_re :=
    reflectedCauchyShiftedStagePoint_tailAnchorCentered_mem_rightHalfPlane
      hanchor hτ hz hv
  have hbase_arg :=
    abs_argumentVector_reflectedCauchyShiftedStagePoint_tailAnchorCentered_le
      hanchor hτ hz hv
  intro j
  refine Fin.addCases ?_ ?_ j
  · intro i
    simp only [osiiTimeArgumentVector]
    rw [reflectedCauchyShiftedStagePoint_targetHubBox_left]
    simpa only [Complex.ofReal_mul, Complex.ofReal_sub] using
      (abs_arg_add_ofReal_le
        (hbase_re (Fin.castAdd (m + 1) i))
        (targetHub_real_shift_nonnegative
          (hhub (Fin.rev i).succ) hu)).trans
        (hbase_arg (Fin.castAdd (m + 1) i))
  · intro r
    refine Fin.cases ?_ (fun i => ?_) r
    · simp only [osiiTimeArgumentVector]
      rw [reflectedMixedDiagonal_bridge,
        reflectedCauchyShiftedStagePoint_targetHubBox_bridge]
      simp only [abs_zero]
      rw [Complex.arg_ofReal_of_nonneg hτ.2.1.le]
      simp
    · simp only [osiiTimeArgumentVector]
      rw [reflectedCauchyShiftedStagePoint_targetHubBox_right]
      simpa only [Complex.ofReal_mul, Complex.ofReal_sub] using
        (abs_arg_add_ofReal_le
          (hbase_re (Fin.natAdd m i.succ))
          (targetHub_real_shift_nonnegative
            (hhub i.succ) hu)).trans
          (hbase_arg (Fin.natAdd m i.succ))

/-- The zero-anchor scalar-stage point over the same box stays in the
product right half-plane. -/
theorem
    zeroAnchorShiftedStagePoint_targetHubBox_mem_rightHalfPlane
    {m : ℕ}
    {anchor hub : Fin (m + 1) → ℝ}
    {τ : Fin (m + (m + 1)) → ℝ}
    {z : Fin m → ℂ}
    {u v : ℝ}
    (hanchor :
      anchor ∈ section43TimeStrictPositiveRegion (m + 1))
    (hhub : ∀ i, anchor i ≤ hub i)
    (hτ : ReflectedTimeDominatesTailAnchor anchor τ)
    (hz : z ∈ osiiTimeRightHalfPlane m)
    (hu : u ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Icc (0 : ℝ) 1) :
    zeroAnchorShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
      osiiTimeRightHalfPlane (m + (m + 1)) := by
  have hbase :=
    zeroAnchorShiftedStagePoint_tailAnchorCentered_mem_rightHalfPlane
      hanchor hτ hz hv
  have hτpos := hτ.strictPositive hanchor
  intro j
  refine Fin.addCases ?_ ?_ j
  · intro i
    rw [zeroAnchorShiftedStagePoint_left]
    simpa using hτpos (Fin.castAdd (m + 1) i)
  · intro r
    refine Fin.cases ?_ (fun i => ?_) r
    · rw [zeroAnchorShiftedStagePoint_bridge]
      exact hτ.2.1
    · rw [zeroAnchorShiftedStagePoint_targetHubBox_right]
      have hshift :
          0 ≤ u * (hub i.succ - anchor i.succ) :=
        targetHub_real_shift_nonnegative (hhub i.succ) hu
      simpa using
        add_pos_of_pos_of_nonneg
          (hbase (Fin.natAdd m i.succ)) hshift

/-- The zero-anchor scalar-stage arguments obey the same generated diagonal
bound throughout the target-and-hub box. -/
theorem
    abs_argumentVector_zeroAnchorShiftedStagePoint_targetHubBox_le
    {m : ℕ}
    {anchor hub : Fin (m + 1) → ℝ}
    {τ : Fin (m + (m + 1)) → ℝ}
    {z : Fin m → ℂ}
    {u v : ℝ}
    (hanchor :
      anchor ∈ section43TimeStrictPositiveRegion (m + 1))
    (hhub : ∀ i, anchor i ≤ hub i)
    (hτ : ReflectedTimeDominatesTailAnchor anchor τ)
    (hz : z ∈ osiiTimeRightHalfPlane m)
    (hu : u ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Icc (0 : ℝ) 1) :
    ∀ j,
      |osiiTimeArgumentVector
          (zeroAnchorShiftedStagePoint τ
            (tailAnchorTargetHubBoxPoint anchor hub z u v)) j| ≤
        |reflectedMixedDiagonal z j| := by
  have hbase_re :=
    zeroAnchorShiftedStagePoint_tailAnchorCentered_mem_rightHalfPlane
      hanchor hτ hz hv
  have hbase_arg :=
    abs_argumentVector_zeroAnchorShiftedStagePoint_tailAnchorCentered_le
      hanchor hτ hz hv
  intro j
  refine Fin.addCases ?_ ?_ j
  · intro i
    simpa [osiiTimeArgumentVector,
      zeroAnchorShiftedStagePoint_left] using
      hbase_arg (Fin.castAdd (m + 1) i)
  · intro r
    refine Fin.cases ?_ (fun i => ?_) r
    · simpa [osiiTimeArgumentVector,
        zeroAnchorShiftedStagePoint_bridge] using
        hbase_arg (Fin.natAdd m (0 : Fin (m + 1)))
    · simp only [osiiTimeArgumentVector]
      rw [zeroAnchorShiftedStagePoint_targetHubBox_right]
      simpa only [Complex.ofReal_mul, Complex.ofReal_sub] using
        (abs_arg_add_ofReal_le
          (hbase_re (Fin.natAdd m i.succ))
          (targetHub_real_shift_nonnegative
            (hhub i.succ) hu)).trans
          (hbase_arg (Fin.natAdd m i.succ))

/-- The reflected-Cauchy scalar-stage map over cutoff time and the compact
target-and-hub parameter square. -/
def reflectedCauchyTailAnchorTargetHubBoxStageMap
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ) :
    ((Fin (m + (m + 1)) → ℝ) × (ℝ × ℝ)) →
      (Fin (m + (m + 1)) → ℂ) :=
  fun p =>
    reflectedCauchyShiftedStagePoint p.1
      (tailAnchorTargetHubBoxPoint anchor hub z p.2.1 p.2.2)

theorem continuous_reflectedCauchyTailAnchorTargetHubBoxStageMap
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ) :
    Continuous
      (reflectedCauchyTailAnchorTargetHubBoxStageMap anchor hub z) := by
  apply continuous_pi
  intro j
  refine Fin.addCases ?_ ?_ j
  · intro i
    simp only [reflectedCauchyTailAnchorTargetHubBoxStageMap,
      reflectedCauchyShiftedStagePoint_targetHubBox_left,
      reflectedCauchyShiftedStagePoint_tailAnchorCentered_left]
    fun_prop
  · intro r
    refine Fin.cases ?_ (fun i => ?_) r
    · simp only [reflectedCauchyTailAnchorTargetHubBoxStageMap,
        reflectedCauchyShiftedStagePoint_targetHubBox_bridge]
      fun_prop
    · simp only [reflectedCauchyTailAnchorTargetHubBoxStageMap,
        reflectedCauchyShiftedStagePoint_targetHubBox_right,
        reflectedCauchyShiftedStagePoint_tailAnchorCentered_right]
      fun_prop

/-- The zero-anchor scalar-stage map over the same parameter square. -/
def zeroAnchorTailAnchorTargetHubBoxStageMap
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ) :
    ((Fin (m + (m + 1)) → ℝ) × (ℝ × ℝ)) →
      (Fin (m + (m + 1)) → ℂ) :=
  fun p =>
    zeroAnchorShiftedStagePoint p.1
      (tailAnchorTargetHubBoxPoint anchor hub z p.2.1 p.2.2)

theorem continuous_zeroAnchorTailAnchorTargetHubBoxStageMap
    {m : ℕ}
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ) :
    Continuous
      (zeroAnchorTailAnchorTargetHubBoxStageMap anchor hub z) := by
  apply continuous_pi
  intro j
  refine Fin.addCases ?_ ?_ j
  · intro i
    simp only [zeroAnchorTailAnchorTargetHubBoxStageMap,
      zeroAnchorShiftedStagePoint_left]
    fun_prop
  · intro r
    refine Fin.cases ?_ (fun i => ?_) r
    · simp only [zeroAnchorTailAnchorTargetHubBoxStageMap,
        zeroAnchorShiftedStagePoint_bridge]
      fun_prop
    · simp only [zeroAnchorTailAnchorTargetHubBoxStageMap,
        zeroAnchorShiftedStagePoint_targetHubBox_right,
        zeroAnchorShiftedStagePoint_tailAnchorCentered_right]
      fun_prop

/-- An open cutoff-time neighborhood preserving both scalar-stage maps over
the complete target-and-hub parameter square. -/
structure TailAnchorTargetHubBoxTimeRegionData
    {d m : ℕ} [NeZero d]
    (A : OSIITimeContinuationStage d (m + (m + 1)))
    (anchor hub : Fin (m + 1) → ℝ)
    (z : Fin m → ℂ)
    (J : Set (Fin (m + (m + 1)) → ℝ)) where
  region : Set (Fin (m + (m + 1)) → ℝ)
  region_open : IsOpen region
  compactCarrier_subset : J ⊆ region
  region_positive :
    region ⊆ section43TimeStrictPositiveRegion (m + (m + 1))
  reflectedCauchy_box_mem :
    ∀ τ ∈ region,
      ∀ u ∈ Set.Icc (0 : ℝ) 1,
        ∀ v ∈ Set.Icc (0 : ℝ) 1,
          reflectedCauchyShiftedStagePoint τ
              (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
            A.carrier
  zeroAnchor_box_mem :
    ∀ τ ∈ region,
      ∀ u ∈ Set.Icc (0 : ℝ) 1,
        ∀ v ∈ Set.Icc (0 : ℝ) 1,
          zeroAnchorShiftedStagePoint τ
              (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
            A.carrier

namespace TailAnchorTargetHubBoxTimeRegionData

/-- A cutoff supported in the selected region keeps every reflected Cauchy
box point inside the scalar moving-slice carrier. -/
theorem reflectedCauchyCenter_box_mem_reflectedMovingSliceCarrier
    {d m : ℕ} [NeZero d]
    {A : OSIITimeContinuationStage d (m + (m + 1))}
    {anchor hub : Fin (m + 1) → ℝ}
    {z : Fin m → ℂ}
    {J : Set (Fin (m + (m + 1)) → ℝ)}
    (R : TailAnchorTargetHubBoxTimeRegionData A anchor hub z J)
    (η : SchwartzMap (Fin (m + (m + 1)) → ℝ) ℂ)
    (hη :
      tsupport
          (η : (Fin (m + (m + 1)) → ℝ) → ℂ) ⊆
        R.region)
    {u v : ℝ}
    (hu : u ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Icc (0 : ℝ) 1) :
    reflectedCauchyCenter
        (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
      reflectedMovingSliceCarrier A η := by
  intro τ hτ
  change
    reflectedCauchyShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
      A.carrier
  exact R.reflectedCauchy_box_mem τ (hη hτ) u hu v hv

/-- The zero-anchor pair has the same box-wide moving-slice coverage. -/
theorem zeroAnchorPair_box_mem_reflectedMovingSliceCarrier
    {d m : ℕ} [NeZero d]
    {A : OSIITimeContinuationStage d (m + (m + 1))}
    {anchor hub : Fin (m + 1) → ℝ}
    {z : Fin m → ℂ}
    {J : Set (Fin (m + (m + 1)) → ℝ)}
    (R : TailAnchorTargetHubBoxTimeRegionData A anchor hub z J)
    (η : SchwartzMap (Fin (m + (m + 1)) → ℝ) ℂ)
    (hη :
      tsupport
          (η : (Fin (m + (m + 1)) → ℝ) → ℂ) ⊆
        R.region)
    {u v : ℝ}
    (hu : u ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Icc (0 : ℝ) 1) :
    reflectedAnchorPair (0 : Fin m → ℂ)
        (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
      reflectedMovingSliceCarrier A η := by
  intro τ hτ
  change
    zeroAnchorShiftedStagePoint τ
        (tailAnchorTargetHubBoxPoint anchor hub z u v) ∈
      A.carrier
  exact R.zeroAnchor_box_mem τ (hη hτ) u hu v hv

end TailAnchorTargetHubBoxTimeRegionData

end OSIIChapterV
end OSReconstruction
