/- Modified for source distribution, 2026-09-10: unused declarations/imports
and development comments removed; retained mathematical statements unchanged. -/
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIITimeParametricContinuation
import OSReconstruction.SCV.IdentityTheorem






















noncomputable section

open Complex Topology
open scoped Classical

namespace OSReconstruction
namespace OSIIChapterV

/-- An admissible Chapter V split `k = n + m - 1`.

The two positive arities index the Hilbert vectors whose scalar product gives
the local candidate on this generator domain. -/
structure GeneratorIndex (k : ℕ) where
  n : ℕ
  m : ℕ
  hn : 1 ≤ n
  hm : 1 ≤ m
  hnm : k = n + m - 1

namespace GeneratorIndex

/-- The chronological gap selected by an admissible Chapter V split. -/
def toGap {k : ℕ} (i : GeneratorIndex k) : Fin k :=
  ⟨i.n - 1, by
    have hn := i.hn
    have hm := i.hm
    have hnm := i.hnm
    have hOne : 1 ≤ i.n + i.m := by omega
    have hsum : k + 1 = i.n + i.m := by
      calc
        k + 1 = (i.n + i.m - 1) + 1 := congrArg (· + 1) hnm
        _ = i.n + i.m := Nat.sub_add_cancel hOne
    omega⟩

/-- The admissible split associated to an existing chronological gap. -/
def ofGap {k : ℕ} (a : Fin k) : GeneratorIndex k where
  n := a.1 + 1
  m := k - a.1
  hn := by omega
  hm := by omega
  hnm := by omega

@[simp]
theorem ofGap_toGap {k : ℕ} (i : GeneratorIndex k) :
    ofGap i.toGap = i := by
  rcases i with ⟨n, m, hn, hm, hnm⟩
  simp only [ofGap, toGap]
  congr <;> omega

@[simp]
theorem toGap_ofGap {k : ℕ} (a : Fin k) :
    (ofGap a).toGap = a := by
  apply Fin.ext
  simp [ofGap, toGap]

@[simp]
theorem n_eq_toGap_add_one {k : ℕ} (i : GeneratorIndex k) :
    i.n = i.toGap.1 + 1 := by
  rcases i with ⟨n, m, hn, hm, hnm⟩
  simp only [toGap]
  omega

@[simp]
theorem m_eq_k_sub_toGap {k : ℕ} (i : GeneratorIndex k) :
    i.m = k - i.toGap.1 := by
  rcases i with ⟨n, m, hn, hm, hnm⟩
  simp only [toGap]
  have hOne : 1 ≤ n + m := by omega
  have hsum : k + 1 = n + m := by
    calc
      k + 1 = (n + m - 1) + 1 := congrArg (· + 1) hnm
      _ = n + m := Nat.sub_add_cancel hOne
  omega

/-- Chapter V generator splits are exactly the existing chronological gaps. -/
def equivGap (k : ℕ) : GeneratorIndex k ≃ Fin k where
  toFun := toGap
  invFun := ofGap
  left_inv := ofGap_toGap
  right_inv := toGap_ofGap

end GeneratorIndex

/-- Local distribution-valued candidates on the mixed Chapter V generator
domains, together with exactly the overlap compatibility needed for gluing. -/
structure GeneratorFamily (d k : ℕ) where
  domain : GeneratorIndex k → Set (OSIITimeGapSpace k)
  domain_open : ∀ i, IsOpen (domain i)
  distribution :
    GeneratorIndex k →
      OSIITimeGapSpace k → OSIISpatialDistribution d k
  weaklyHolomorphic :
    ∀ i, OSIIWeaklyHolomorphicOn (distribution i) (domain i)
  compatible :
    ∀ i j, Set.EqOn (distribution i) (distribution j)
      (domain i ∩ domain j)

namespace GeneratorFamily

variable {d k : ℕ}

/-- The mixed-domain union generated by all admissible Hilbert-vector
splittings. -/
def generatingUnion (G : GeneratorFamily d k) :
    Set (OSIITimeGapSpace k) :=
  ⋃ i : GeneratorIndex k, G.domain i

theorem generatingUnion_open (G : GeneratorFamily d k) :
    IsOpen G.generatingUnion := by
  exact isOpen_iUnion G.domain_open

/-- The distribution-valued candidate obtained by gluing all generator
splits. -/
def gluedDistribution (G : GeneratorFamily d k) :
    OSIITimeGapSpace k → OSIISpatialDistribution d k :=
  SCV.glued_iUnion G.domain G.distribution

/-- The glued candidate agrees with each local Hilbert-pairing candidate on
its complete generator domain. -/
theorem gluedDistribution_eqOn_domain
    (G : GeneratorFamily d k) (i : GeneratorIndex k) :
    Set.EqOn G.gluedDistribution (G.distribution i) (G.domain i) := by
  exact SCV.glued_iUnion_eqOn G.compatible i

theorem gluedDistribution_apply
    (G : GeneratorFamily d k)
    (χ : SchwartzMap (Section43SpatialSpace d k) ℂ) :
    (fun ζ => G.gluedDistribution ζ χ) =
      SCV.glued_iUnion G.domain
        (fun i ζ => G.distribution i ζ χ) := by
  funext ζ
  classical
  simp only [gluedDistribution, SCV.glued_iUnion]
  split_ifs <;> rfl

/-- Pairwise-compatible generator candidates are weakly holomorphic after
gluing on their union.  This is the gluing half of
`(P_N) -> (A_{N+1})`; no envelope theorem is used here. -/
theorem gluedDistribution_weaklyHolomorphic
    (G : GeneratorFamily d k) :
    OSIIWeaklyHolomorphicOn G.gluedDistribution G.generatingUnion := by
  intro χ
  rw [G.gluedDistribution_apply χ]
  apply SCV.differentiableOn_glued_iUnion
  · intro ζ hζ
    exact hζ
  · exact G.domain_open
  · intro i
    exact G.weaklyHolomorphic i χ
  · intro i j ζ hζ
    exact congrArg
      (fun T : OSIISpatialDistribution d k => T χ)
      (G.compatible i j hζ)

/-- The generating union itself is an honest scalar-continuation stage. -/
def toTimeContinuationStage
    (G : GeneratorFamily d k) :
    OSIITimeContinuationStage d k where
  carrier := G.generatingUnion
  carrier_open := G.generatingUnion_open
  distribution := G.gluedDistribution
  weaklyHolomorphic := G.gluedDistribution_weaklyHolomorphic

end GeneratorFamily

/-- Distribution-valued weakly holomorphic families satisfy uniqueness on a
connected carrier as soon as they agree on a nonempty complex-open seed.

The proof applies the scalar several-variable identity theorem after pairing
with every spatial Schwartz test and then uses extensionality of continuous
linear functionals. -/
theorem weaklyHolomorphic_eqOn_of_eqOn_open
    {d k : ℕ}
    {U V : Set (OSIITimeGapSpace k)}
    (hU_open : IsOpen U)
    (hU_connected : IsConnected U)
    (hV_open : IsOpen V)
    (hV_nonempty : V.Nonempty)
    (hVU : V ⊆ U)
    {F G : OSIITimeGapSpace k → OSIISpatialDistribution d k}
    (hF : OSIIWeaklyHolomorphicOn F U)
    (hG : OSIIWeaklyHolomorphicOn G U)
    (hEq : Set.EqOn F G V) :
    Set.EqOn F G U := by
  rcases hV_nonempty with ⟨ζ₀, hζ₀V⟩
  intro ζ hζU
  apply ContinuousLinearMap.ext
  intro χ
  have hlocal :
      (fun w => F w χ) =ᶠ[nhds ζ₀] (fun w => G w χ) := by
    rw [Filter.eventuallyEq_iff_exists_mem]
    refine ⟨V, hV_open.mem_nhds hζ₀V, ?_⟩
    intro w hw
    exact congrArg
      (fun T : OSIISpatialDistribution d k => T χ)
      (hEq hw)
  exact
    identity_theorem_SCV
      hU_open hU_connected (hF χ) (hG χ)
      (hVU hζ₀V) hlocal hζU

namespace EnvelopeExtension

variable {d k : ℕ} {G : GeneratorFamily d k}
  {U : Set (OSIITimeGapSpace k)}

end EnvelopeExtension

end OSIIChapterV
end OSReconstruction
