/- Modified for source distribution, 2026-09-10: unused declarations/imports
and development comments removed; retained mathematical statements unchanged. -/
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVHilbertTaylor
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIPositiveTimeHilbertSource


















noncomputable section

open Complex Topology
open scoped BigOperators Classical

namespace OSReconstruction
namespace OSIIChapterV

variable {d : ℕ} [NeZero d]

/-- The reflected scalar Gram coefficient of two homogeneous positive-time
Taylor sources. -/
def positiveTimeTaylorScalarGram
    (OS : OsterwalderSchraderAxioms d)
    (n : ℕ)
    (sourceTerm : ℕ → euclideanPositiveTimeSubmodule (d := d) n)
    (p q : ℕ) : ℂ :=
  OS.S (n + n)
    (ZeroDiagonalSchwartz.ofClassical
      ((sourceTerm p).1.osConjTensorProduct (sourceTerm q).1))

/-- Concrete OS Hilbert Taylor Gram data generated by homogeneous
positive-time Schwartz sources. -/
def positiveTimeTaylorGramData
    (OS : OsterwalderSchraderAxioms d)
    (n : ℕ)
    (sourceTerm : ℕ → euclideanPositiveTimeSubmodule (d := d) n) :
    HilbertTaylorGramData (OSHilbertSpace OS) where
  homogeneousTerm p :=
    osiiPositiveTimeSingleVectorCLM OS n (sourceTerm p)
  scalarGram :=
    positiveTimeTaylorScalarGram OS n sourceTerm
  inner_homogeneousTerm_eq_scalarGram p q :=
    osiiPositiveTimeSingleVectorCLM_inner_eq_schwinger
      OS n n (sourceTerm p) (sourceTerm q)

@[simp] theorem positiveTimeTaylorGramData_homogeneousTerm
    (OS : OsterwalderSchraderAxioms d)
    (n : ℕ)
    (sourceTerm : ℕ → euclideanPositiveTimeSubmodule (d := d) n)
    (p : ℕ) :
    (positiveTimeTaylorGramData OS n sourceTerm).homogeneousTerm p =
      osiiPositiveTimeSingleVectorCLM OS n (sourceTerm p) :=
  rfl

@[simp] theorem positiveTimeTaylorGramData_scalarGram
    (OS : OsterwalderSchraderAxioms d)
    (n : ℕ)
    (sourceTerm : ℕ → euclideanPositiveTimeSubmodule (d := d) n)
    (p q : ℕ) :
    (positiveTimeTaylorGramData OS n sourceTerm).scalarGram p q =
      positiveTimeTaylorScalarGram OS n sourceTerm p q :=
  rfl

/-- The Hilbert Taylor polynomial is the positive-time source-vector map
applied to the finite sum of homogeneous Schwartz coefficients. -/
theorem positiveTimeTaylorGramData_partialSum_eq
    (OS : OsterwalderSchraderAxioms d)
    (n : ℕ)
    (sourceTerm : ℕ → euclideanPositiveTimeSubmodule (d := d) n)
    (N : ℕ) :
    (positiveTimeTaylorGramData OS n sourceTerm).partialSum N =
      osiiPositiveTimeSingleVectorCLM OS n
        (∑ p ∈ Finset.range N, sourceTerm p) := by
  simp only [HilbertTaylorGramData.partialSum,
    positiveTimeTaylorGramData_homogeneousTerm, map_sum]

end OSIIChapterV
end OSReconstruction
