/- Modified for source distribution, 2026-09-10: unused declarations/imports
and development comments removed; retained mathematical statements unchanged. -/
import Init
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIProductionRadialFixedMajorant
import OSReconstruction.Wightman.Reconstruction.WickRotation.OSToWightmanOSIIChapterVIBlockRadialSelectedBlockMZUniform
import OSReconstruction.Wightman.Reconstruction.WickRotation.deprecated.OSFixedOrderGrowth










noncomputable section

open Complex Metric Set
open scoped Classical

namespace OSReconstruction

/-- The fixed finite Schwartz seminorm family generated by the single E0'
Sobolev index. It is independent of particle number. -/
def osiiE0PrimeHilbertSeminorms
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSFixedOrderGrowthCondition d OS) : Finset (Nat × Nat) :=
  ({0, lgc.sobolev_index} : Finset Nat).product
    (Finset.range (lgc.sobolev_index + 1))

/-- The fixed tensor-product coefficient generated by the single E0'
Sobolev index. -/
def osiiE0PrimeHilbertTensorFactor
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSFixedOrderGrowthCondition d OS) : Real :=
  2 ^ lgc.sobolev_index *
    ∑ i ∈ Finset.range (lgc.sobolev_index + 1),
      (lgc.sobolev_index.choose i : Real) * (1 + 1)

/-- Exact E0' arity coefficient for a positive-time Hilbert norm square. -/
def osiiE0PrimeHilbertNormSqFactor
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSFixedOrderGrowthCondition d OS)
    (r : Nat) : Real :=
  (lgc.alpha * lgc.beta ^ (r + r) *
      ((r + r).factorial : Real) ^ lgc.gamma) *
    osiiE0PrimeHilbertTensorFactor lgc

/-- The real factorial exponent in E0' is absorbed by one natural
arity exponent without assuming `gamma` is nonnegative.  Negative
factorial powers are already at most one; the ceiling of `max gamma 0`
is the uniform integer budget used by the later all-arity majorant. -/
theorem natFactorial_rpow_le_arityPow
    (n : Nat) (gamma : Real) :
    (n.factorial : Real) ^ gamma <=
      (n : Real) ^ (n * Nat.ceil (max gamma 0)) := by
  let g := Nat.ceil (max gamma 0)
  have hfac_one : (1 : Real) <= n.factorial := by
    exact_mod_cast Nat.one_le_iff_ne_zero.mpr (Nat.factorial_ne_zero n)
  have hgamma : gamma <= (g : Real) := by
    dsimp [g]
    exact le_trans (le_max_left _ _) (Nat.le_ceil _)
  have hfac_exp :
      (n.factorial : Real) ^ gamma <= (n.factorial : Real) ^ (g : Real) :=
    Real.rpow_le_rpow_of_exponent_le hfac_one hgamma
  have hfac_pow :
      (n.factorial : Real) ^ (g : Real) = (n.factorial : Real) ^ g := by
    rw [Real.rpow_natCast]
  have hfac_le : (n.factorial : Real) <= (n : Real) ^ n := by
    exact_mod_cast Nat.factorial_le_pow n
  have hpow :
      (n.factorial : Real) ^ g <= ((n : Real) ^ n) ^ g :=
    pow_le_pow_left₀ (by positivity) hfac_le g
  calc
    (n.factorial : Real) ^ gamma <=
        (n.factorial : Real) ^ (g : Real) := hfac_exp
    _ = (n.factorial : Real) ^ g := hfac_pow
    _ <= ((n : Real) ^ n) ^ g := hpow
    _ = (n : Real) ^ (n * g) := by rw [← pow_mul]

/-- A fixed nonnegative exponential base costs only one fixed coefficient
and a natural arity exponent.  The `max a 1` front factor handles arity one
exactly; for arity at least two, the ceiling is absorbed by `n ^ A`.
This is the companion to `natFactorial_rpow_le_arityPow` for the fixed E0'
and source-native exponential bases. -/
theorem nonneg_pow_le_max_mul_arityPow
    (a : Real) (ha : 0 <= a) (n : Nat) (hn : 0 < n) :
    a ^ n <=
      max a 1 * (n : Real) ^ (n * Nat.ceil (max a 1)) := by
  let b : Real := max a 1
  let A : Nat := Nat.ceil b
  have hab : a <= b := by
    dsimp [b]
    exact le_max_left _ _
  have hb_one : (1 : Real) <= b := by
    dsimp [b]
    exact le_max_right _ _
  have hbA : b <= (A : Real) := by
    dsimp [A]
    exact Nat.le_ceil _
  have hA_two_nat : A <= 2 ^ A := by
    simpa [Nat.choose_one_right] using Nat.choose_le_two_pow A 1
  have hA_two : (A : Real) <= (2 : Real) ^ A := by
    exact_mod_cast hA_two_nat
  by_cases hn_one : n = 1
  · subst n
    simpa [b, A] using hab
  · have hn_two : 2 <= n := by omega
    have htwo_n : (2 : Real) <= n := by exact_mod_cast hn_two
    have htwo_pow : (2 : Real) ^ A <= (n : Real) ^ A :=
      pow_le_pow_left₀ (by norm_num) htwo_n A
    have hb_npow : b <= (n : Real) ^ A :=
      hbA.trans (hA_two.trans htwo_pow)
    have ha_pow : a ^ n <= b ^ n :=
      pow_le_pow_left₀ ha hab n
    have hb_pow : b ^ n <= ((n : Real) ^ A) ^ n :=
      pow_le_pow_left₀ (by positivity) hb_npow n
    have hpow_nonneg : 0 <= (n : Real) ^ (n * A) := by positivity
    calc
      a ^ n <= b ^ n := ha_pow
      _ <= ((n : Real) ^ A) ^ n := hb_pow
      _ = (n : Real) ^ (A * n) := by rw [← pow_mul]
      _ = (n : Real) ^ (n * A) := by rw [Nat.mul_comm A n]
      _ = 1 * (n : Real) ^ (n * A) := by ring
      _ <= b * (n : Real) ^ (n * A) :=
        mul_le_mul_of_nonneg_right hb_one hpow_nonneg

/-- The standard arity shape is monotone when both its base arity and its
linear exponent increase.  This lets a selected split use the ambient packet
arity without retaining a separate left/right exponent. -/
theorem arityPow_le_arityPow_of_le
    (r k T : Nat) (hr : 0 < r) (hrk : r <= k) :
    (r : Real) ^ (r * T) <= (k : Real) ^ (k * T) := by
  have hk_pos : 0 < k := lt_of_lt_of_le hr hrk
  have hrk_real : (r : Real) <= k := by
    exact_mod_cast hrk
  have hk_one : (1 : Real) <= k := by
    exact_mod_cast hk_pos
  calc
    (r : Real) ^ (r * T) <= (k : Real) ^ (r * T) :=
      pow_le_pow_left₀ (by positivity) hrk_real _
    _ <= (k : Real) ^ (k * T) :=
      pow_le_pow_right₀ hk_one (Nat.mul_le_mul_right T hrk)

/-- A doubled arity base can be returned to the standard `r ^ (r * t)`
shape at the price of a fixed power of two and four times the exponent.
This is the exact conversion needed after applying the E0' estimate at
the reflected self-pair arity `2 * r`. -/
theorem two_mul_arityPow_le_two_pow_mul_arityPow
    (r T : Nat) (hr : 0 < r) :
    (((2 * r : Nat) : Real) ^ ((2 * r) * T)) <=
      (2 : Real) ^ (2 * T) * (r : Real) ^ (r * (4 * T)) := by
  by_cases hr_one : r = 1
  · subst r
    simp
  · have hr_two : 2 <= r := by omega
    have hr_real : (2 : Real) <= r := by exact_mod_cast hr_two
    have hbase : ((2 * r : Nat) : Real) <= (r : Real) * (r : Real) := by
      norm_num
      nlinarith
    have hpow :
        (((2 * r : Nat) : Real) ^ ((2 * r) * T)) <=
          ((r : Real) * (r : Real)) ^ ((2 * r) * T) :=
      pow_le_pow_left₀ (by positivity) hbase _
    have htwo : (1 : Real) <= (2 : Real) ^ (2 * T) :=
      one_le_pow₀ (by norm_num)
    have hrpow_nonneg : 0 <= (r : Real) ^ (r * (4 * T)) := by positivity
    calc
      (((2 * r : Nat) : Real) ^ ((2 * r) * T)) <=
          ((r : Real) * (r : Real)) ^ ((2 * r) * T) := hpow
      _ = (r : Real) ^ ((2 * r) * T + (2 * r) * T) := by
        rw [mul_pow, ← pow_add]
      _ = (r : Real) ^ (r * (4 * T)) := by congr 1 <;> ring
      _ = 1 * (r : Real) ^ (r * (4 * T)) := by ring
      _ <= (2 : Real) ^ (2 * T) * (r : Real) ^ (r * (4 * T)) :=
        mul_le_mul_of_nonneg_right htwo hrpow_nonneg

/-- The corrected reflected-source seminorm family has order `2 * r * s`;
in particular it is not independent of particle arity. -/
def osiiArityLinearHilbertSeminorms
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS)
    (r : Nat) : Finset (Nat × Nat) :=
  Finset.Iic ((r + r) * lgc.sobolev_index,
    (r + r) * lgc.sobolev_index)

/-- Taking the maximum over the complete Schwartz rectangle avoids the
cardinality loss in the arbitrary finite-family rotation estimate. -/
theorem finsetSup_Iic_osiiEuclideanRotateSchwartz_le
    (d r L : Nat) [NeZero d]
    (R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (hR : R.transpose * R = 1)
    (f : SchwartzNPoint d r) :
    (Finset.Iic (L, L)).sup
        (schwartzSeminormFamily Real (NPointDomain d r) Complex)
        (osiiEuclideanRotateSchwartz R hR f) ≤
      (d + 1 : Real) ^ (2 * L) *
        (Finset.Iic (L, L)).sup
          (schwartzSeminormFamily Real (NPointDomain d r) Complex) f := by
  let Q : Real :=
    (Finset.Iic (L, L)).sup
      (schwartzSeminormFamily Real (NPointDomain d r) Complex) f
  have hQ : 0 ≤ Q := apply_nonneg _ _
  have hdimension : (1 : Real) ≤ (d + 1 : Real) := by
    exact_mod_cast Nat.succ_le_succ (Nat.zero_le d)
  apply Seminorm.finset_sup_apply_le (by positivity)
  intro ⟨p, q⟩ hpq
  have hp : p ≤ L := (Finset.mem_Iic.mp hpq).1
  have hq : q ≤ L := (Finset.mem_Iic.mp hpq).2
  have hdegree : p + q ≤ 2 * L := by omega
  have hsource : SchwartzMap.seminorm Real p q f ≤ Q := by
    simpa only [Q, SchwartzMap.schwartzSeminormFamily_apply] using
      (Seminorm.le_finset_sup_apply
        (p := schwartzSeminormFamily Real
          (NPointDomain d r) Complex) hpq)
  calc
    SchwartzMap.seminorm Real p q
        (osiiEuclideanRotateSchwartz R hR f) ≤
      (d + 1 : Real) ^ (p + q) *
        SchwartzMap.seminorm Real p q f :=
      seminorm_osiiEuclideanRotateSchwartz_le R hR p q f
    _ ≤ (d + 1 : Real) ^ (p + q) * Q := by gcongr
    _ ≤ (d + 1 : Real) ^ (2 * L) * Q := by
      exact mul_le_mul_of_nonneg_right
        (pow_le_pow_right₀ hdimension hdegree) hQ

/-- The reflected-left source has the same complete-rectangle rotation
constant as the unreflected right source. -/
theorem finsetSup_Iic_timeReflect_rotate_timeReflect_le
    (d r L : Nat) [NeZero d]
    (R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (hR : R.transpose * R = 1)
    (f : SchwartzNPoint d r) :
    (Finset.Iic (L, L)).sup
        (schwartzSeminormFamily Real (NPointDomain d r) Complex)
        ((osiiEuclideanRotateSchwartz R hR f.timeReflect).timeReflect) ≤
      (d + 1 : Real) ^ (2 * L) *
        (Finset.Iic (L, L)).sup
          (schwartzSeminormFamily Real (NPointDomain d r) Complex) f := by
  let Q : Real :=
    (Finset.Iic (L, L)).sup
      (schwartzSeminormFamily Real (NPointDomain d r) Complex) f
  have hQ : 0 ≤ Q := apply_nonneg _ _
  have hdimension : (1 : Real) ≤ (d + 1 : Real) := by
    exact_mod_cast Nat.succ_le_succ (Nat.zero_le d)
  apply Seminorm.finset_sup_apply_le (by positivity)
  intro ⟨p, q⟩ hpq
  have hp : p ≤ L := (Finset.mem_Iic.mp hpq).1
  have hq : q ≤ L := (Finset.mem_Iic.mp hpq).2
  have hdegree : p + q ≤ 2 * L := by omega
  have hsource : SchwartzMap.seminorm Real p q f ≤ Q := by
    simpa only [Q, SchwartzMap.schwartzSeminormFamily_apply] using
      (Seminorm.le_finset_sup_apply
        (p := schwartzSeminormFamily Real
          (NPointDomain d r) Complex) hpq)
  calc
    SchwartzMap.seminorm Real p q
        ((osiiEuclideanRotateSchwartz R hR f.timeReflect).timeReflect) ≤
      SchwartzMap.seminorm Real p q
        (osiiEuclideanRotateSchwartz R hR f.timeReflect) :=
      SchwartzNPoint.seminorm_timeReflect_le
        (d := d) p q (osiiEuclideanRotateSchwartz R hR f.timeReflect)
    _ ≤ (d + 1 : Real) ^ (p + q) *
        SchwartzMap.seminorm Real p q f.timeReflect :=
      seminorm_osiiEuclideanRotateSchwartz_le R hR p q f.timeReflect
    _ ≤ (d + 1 : Real) ^ (p + q) *
        SchwartzMap.seminorm Real p q f := by
      exact mul_le_mul_of_nonneg_left
        (SchwartzNPoint.seminorm_timeReflect_le (d := d) p q f)
        (by positivity)
    _ ≤ (d + 1 : Real) ^ (p + q) * Q := by gcongr
    _ ≤ (d + 1 : Real) ^ (2 * L) * Q := by
      exact mul_le_mul_of_nonneg_right
        (pow_le_pow_right₀ hdimension hdegree) hQ

/-- The exponential base absorbs both reflected E0' factors and the exact
arity-dependent tensor-product seminorm comparison. -/
def osiiArityLinearHilbertExponentialBase
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) : Real :=
  lgc.beta ^ 2 * (2 : Real) ^ (4 * lgc.sobolev_index)

/-- One natural arity exponent absorbs the corrected reflected exponential
and real factorial growth without fixing the source Schwartz order. -/
def osiiArityLinearHilbertArityRate
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) : Nat :=
  Nat.ceil (max (osiiArityLinearHilbertExponentialBase lgc) 1) +
    4 * Nat.ceil (max lgc.gamma 0)

/-- The corrected Hilbert majorant has a single coefficient selected before
the positive particle arity or source. -/
def osiiArityLinearHilbertArityConstant
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) : Real :=
  2 * lgc.alpha * max (osiiArityLinearHilbertExponentialBase lgc) 1 *
    (2 : Real) ^ (2 * Nat.ceil (max lgc.gamma 0))

theorem osiiArityLinearHilbertArityConstant_nonneg
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) :
    0 <= osiiArityLinearHilbertArityConstant lgc := by
  unfold osiiArityLinearHilbertArityConstant
  exact mul_nonneg
    (mul_nonneg (mul_nonneg (by norm_num) lgc.alpha_pos.le)
      (le_trans (by norm_num) (le_max_right _ _)))
    (by positivity)

/-- Corrected arity-linear E0' supplies the exact fixed-coefficient,
all-arity majorant needed before the Chapter VI normalized induction. -/
theorem osiiArityLinearHilbertNormSqFactor_le_arityMajorant
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS)
    (r : Nat) (hr : 0 < r) :
    (lgc.alpha * lgc.beta ^ (r + r) *
        ((r + r).factorial : Real) ^ lgc.gamma) *
        (2 : Real) ^
          ((r + r) * lgc.sobolev_index +
            (r + r) * lgc.sobolev_index + 1) <=
      osiiArityLinearHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) := by
  let B : Real := osiiArityLinearHilbertExponentialBase lgc
  let A : Nat := Nat.ceil (max B 1)
  let G : Nat := Nat.ceil (max lgc.gamma 0)
  have hB : 0 <= B := by
    dsimp [B, osiiArityLinearHilbertExponentialBase]
    positivity
  have hexp :
      lgc.beta ^ (r + r) *
          (2 : Real) ^
            ((r + r) * lgc.sobolev_index +
              (r + r) * lgc.sobolev_index + 1) =
        2 * B ^ r := by
    dsimp [B, osiiArityLinearHilbertExponentialBase]
    rw [mul_pow, ← pow_mul, ← pow_mul]
    have hbeta : 2 * r = r + r := by omega
    have htwo :
        (4 * lgc.sobolev_index) * r + 1 =
          (r + r) * lgc.sobolev_index +
            (r + r) * lgc.sobolev_index + 1 := by ring
    rw [hbeta, ← htwo, pow_succ]
    ring
  have hbase :
      B ^ r <= max B 1 * (r : Real) ^ (r * A) := by
    simpa [A] using nonneg_pow_le_max_mul_arityPow B hB r hr
  have hfactorial :
      ((r + r).factorial : Real) ^ lgc.gamma <=
        (2 : Real) ^ (2 * G) * (r : Real) ^ (r * (4 * G)) := by
    calc
      ((r + r).factorial : Real) ^ lgc.gamma <=
          (((2 * r : Nat) : Real) ^ ((2 * r) * G)) := by
            simpa [G, two_mul] using
              natFactorial_rpow_le_arityPow (r + r) lgc.gamma
      _ <= (2 : Real) ^ (2 * G) *
          (r : Real) ^ (r * (4 * G)) :=
            two_mul_arityPow_le_two_pow_mul_arityPow r G hr
  have hfactorial_nonneg :
      0 <= ((r + r).factorial : Real) ^ lgc.gamma := by
    positivity
  have hbase_bound_nonneg :
      0 <= max B 1 * (r : Real) ^ (r * A) := by
    positivity
  calc
    (lgc.alpha * lgc.beta ^ (r + r) *
        ((r + r).factorial : Real) ^ lgc.gamma) *
        (2 : Real) ^
          ((r + r) * lgc.sobolev_index +
            (r + r) * lgc.sobolev_index + 1) =
        2 * lgc.alpha * B ^ r *
          ((r + r).factorial : Real) ^ lgc.gamma := by
            calc
              (lgc.alpha * lgc.beta ^ (r + r) *
                  ((r + r).factorial : Real) ^ lgc.gamma) *
                  (2 : Real) ^
                    ((r + r) * lgc.sobolev_index +
                      (r + r) * lgc.sobolev_index + 1) =
                lgc.alpha *
                  (lgc.beta ^ (r + r) *
                    (2 : Real) ^
                      ((r + r) * lgc.sobolev_index +
                        (r + r) * lgc.sobolev_index + 1)) *
                  ((r + r).factorial : Real) ^ lgc.gamma := by ring
              _ = 2 * lgc.alpha * B ^ r *
                  ((r + r).factorial : Real) ^ lgc.gamma := by
                    rw [hexp]
                    ring
    _ <= 2 * lgc.alpha *
        (max B 1 * (r : Real) ^ (r * A)) *
        ((2 : Real) ^ (2 * G) * (r : Real) ^ (r * (4 * G))) := by
          have hscale : 0 <= (2 : Real) * lgc.alpha :=
            mul_nonneg (by norm_num) lgc.alpha_pos.le
          simpa [mul_assoc] using
            (mul_le_mul_of_nonneg_left
              (mul_le_mul hbase hfactorial hfactorial_nonneg
                hbase_bound_nonneg)
              hscale)
    _ = osiiArityLinearHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) := by
          simp only [osiiArityLinearHilbertArityConstant,
            osiiArityLinearHilbertArityRate]
          change
            2 * lgc.alpha *
              (max B 1 * (r : Real) ^ (r * A)) *
              ((2 : Real) ^ (2 * G) * (r : Real) ^ (r * (4 * G))) =
            (2 * lgc.alpha * max B 1 * (2 : Real) ^ (2 * G)) *
              (r : Real) ^ (r * (A + 4 * G))
          rw [Nat.mul_add, pow_add]
          ring

/-- Every genuine positive-time OS source satisfies the corrected fixed-
coefficient all-arity Hilbert bound, with its necessary arity-linear family
of defining Schwartz seminorms. -/
theorem osiiPositiveTimeSingleVector_norm_sq_arityLinearMajorant_le
    (d r : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS)
    (hr : 0 < r)
    (g : SchwartzNPoint d r)
    (hg : tsupport (g : NPointDomain d r -> Complex) <=
      OrderedPositiveTimeRegion d r) :
    ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 <=
      osiiArityLinearHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) g) ^ 2 := by
  let Q : Real :=
    (osiiArityLinearHilbertSeminorms lgc r).sup
      (schwartzSeminormFamily Real (NPointDomain d r) Complex) g
  have hsource :=
    osiiPositiveTimeSingleVectorCLM_norm_sq_le_arityLinearFinsetSup
      OS lgc g hg
  have hcoefficient :=
    osiiArityLinearHilbertNormSqFactor_le_arityMajorant lgc r hr
  calc
    ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 <=
        ((lgc.alpha * lgc.beta ^ (r + r) *
          ((r + r).factorial : Real) ^ lgc.gamma) *
          (2 : Real) ^
            ((r + r) * lgc.sobolev_index +
              (r + r) * lgc.sobolev_index + 1)) * Q ^ 2 := by
            simpa [Q, osiiArityLinearHilbertSeminorms, mul_assoc] using
              hsource
    _ <= (osiiArityLinearHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc)) * Q ^ 2 :=
          mul_le_mul_of_nonneg_right hcoefficient (sq_nonneg Q)
    _ = osiiArityLinearHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) g) ^ 2 := by
            rfl

/-- Squaring the complete reflected-source rotation estimate contributes
only one dimension-dependent exponential base per particle. -/
def osiiArityLinearRotatedHilbertRotationBase
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) : Real :=
  (d + 1 : Real) ^ (8 * lgc.sobolev_index)

/-- One coefficient controls all rotated reflected Hilbert sources,
including the indispensable single-particle case. -/
def osiiArityLinearRotatedHilbertArityConstant
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) : Real :=
  osiiArityLinearHilbertArityConstant lgc *
    max (osiiArityLinearRotatedHilbertRotationBase lgc) 1

/-- The orthogonal-rotation loss increases the natural arity rate by one
fixed, dimension-dependent quantity. -/
def osiiArityLinearRotatedHilbertArityRate
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSArityLinearGrowthCondition d OS) : Nat :=
  osiiArityLinearHilbertArityRate lgc +
    Nat.ceil (max (osiiArityLinearRotatedHilbertRotationBase lgc) 1)

/-- A complete-rectangle rotation estimate suffices for one corrected E0'
Hilbert bound at every positive source arity. -/
theorem osiiPositiveTimeSingleVector_norm_sq_arityLinearMajorant_of_completeRotation
    (d r : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS)
    (hr : 0 < r)
    (f g : SchwartzNPoint d r)
    (hg : tsupport (g : NPointDomain d r → Complex) ≤
      OrderedPositiveTimeRegion d r)
    (hrotation :
      (osiiArityLinearHilbertSeminorms lgc r).sup
          (schwartzSeminormFamily Real (NPointDomain d r) Complex) g ≤
        (d + 1 : Real) ^
            (2 * ((r + r) * lgc.sobolev_index)) *
          (osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real (NPointDomain d r) Complex) f) :
    ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 ≤
      osiiArityLinearRotatedHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) f) ^ 2 := by
  let Q : Real :=
    (osiiArityLinearHilbertSeminorms lgc r).sup
      (schwartzSeminormFamily Real (NPointDomain d r) Complex) f
  let Qrot : Real :=
    (osiiArityLinearHilbertSeminorms lgc r).sup
      (schwartzSeminormFamily Real (NPointDomain d r) Complex) g
  let C : Real :=
    (d + 1 : Real) ^ (2 * ((r + r) * lgc.sobolev_index))
  let E : Real := osiiArityLinearRotatedHilbertRotationBase lgc
  have hQ : 0 ≤ Q := apply_nonneg _ _
  have hQrot : 0 ≤ Qrot := apply_nonneg _ _
  have hC : 0 ≤ C := by
    dsimp [C]
    positivity
  have hE : 0 ≤ E := by
    dsimp [E, osiiArityLinearRotatedHilbertRotationBase]
    positivity
  have hrotation' : Qrot ≤ C * Q := hrotation
  have hsquare : C ^ 2 = E ^ r := by
    dsimp [C, E, osiiArityLinearRotatedHilbertRotationBase]
    simp only [← pow_mul]
    congr 1
    ring
  have habsorb :
      E ^ r ≤
        max E 1 * (r : Real) ^ (r * Nat.ceil (max E 1)) :=
    nonneg_pow_le_max_mul_arityPow E hE r hr
  have hcoefficient :
      0 ≤ osiiArityLinearHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) :=
    mul_nonneg (osiiArityLinearHilbertArityConstant_nonneg lgc)
      (by positivity)
  have hvector :=
    osiiPositiveTimeSingleVector_norm_sq_arityLinearMajorant_le
      d r OS lgc hr g hg
  calc
    ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 ≤
        osiiArityLinearHilbertArityConstant lgc *
          (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) *
          Qrot ^ 2 := hvector
    _ ≤ osiiArityLinearHilbertArityConstant lgc *
          (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc) *
          (C * Q) ^ 2 := by
            exact mul_le_mul_of_nonneg_left
              (pow_le_pow_left₀ hQrot hrotation' 2) hcoefficient
    _ = (osiiArityLinearHilbertArityConstant lgc * E ^ r *
          (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc)) *
          Q ^ 2 := by
            rw [mul_pow, hsquare]
            ring
    _ ≤ (osiiArityLinearHilbertArityConstant lgc *
          (max E 1 * (r : Real) ^ (r * Nat.ceil (max E 1))) *
          (r : Real) ^ (r * osiiArityLinearHilbertArityRate lgc)) *
          Q ^ 2 := by
            gcongr
            exact osiiArityLinearHilbertArityConstant_nonneg lgc
    _ = osiiArityLinearRotatedHilbertArityConstant lgc *
          (r : Real) ^ (r * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) f) ^ 2 := by
            dsimp [Q, E, osiiArityLinearRotatedHilbertArityConstant,
              osiiArityLinearRotatedHilbertArityRate]
            rw [Nat.mul_add, pow_add]
            ring

/-- The actual rotated-right Hilbert source has a fixed corrected E0'
coefficient and natural rate independent of its rotation and arity. -/
theorem osiiPositiveTimeSingleVector_rotated_norm_sq_arityLinearMajorant_le
    (d r : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS)
    (hr : 0 < r)
    (R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (hR : R.transpose * R = 1)
    (f : SchwartzNPoint d r)
    (hg : tsupport
      (osiiEuclideanRotateSchwartz R hR f : NPointDomain d r → Complex) ≤
        OrderedPositiveTimeRegion d r) :
    ‖osiiPositiveTimeSingleVectorCLM OS r
        ⟨osiiEuclideanRotateSchwartz R hR f, hg⟩‖ ^ 2 ≤
      osiiArityLinearRotatedHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) f) ^ 2 := by
  apply osiiPositiveTimeSingleVector_norm_sq_arityLinearMajorant_of_completeRotation
    d r OS lgc hr f (osiiEuclideanRotateSchwartz R hR f) hg
  simpa [osiiArityLinearHilbertSeminorms] using
    finsetSup_Iic_osiiEuclideanRotateSchwartz_le
      d r ((r + r) * lgc.sobolev_index) R hR f

/-- The reflected-left rotation has exactly the same all-arity coefficient
as the unreflected rotated-right source. -/
theorem osiiPositiveTimeSingleVector_reflectedRotated_norm_sq_arityLinearMajorant_le
    (d r : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS)
    (hr : 0 < r)
    (R : Matrix (Fin (d + 1)) (Fin (d + 1)) Real)
    (hR : R.transpose * R = 1)
    (f : SchwartzNPoint d r)
    (hg : tsupport
      ((osiiEuclideanRotateSchwartz R hR f.timeReflect).timeReflect :
        NPointDomain d r → Complex) ≤
          OrderedPositiveTimeRegion d r) :
    ‖osiiPositiveTimeSingleVectorCLM OS r
        ⟨(osiiEuclideanRotateSchwartz R hR f.timeReflect).timeReflect,
          hg⟩‖ ^ 2 ≤
      osiiArityLinearRotatedHilbertArityConstant lgc *
        (r : Real) ^ (r * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc r).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) f) ^ 2 := by
  apply osiiPositiveTimeSingleVector_norm_sq_arityLinearMajorant_of_completeRotation
    d r OS lgc hr f
      ((osiiEuclideanRotateSchwartz R hR f.timeReflect).timeReflect) hg
  simpa [osiiArityLinearHilbertSeminorms] using
    finsetSup_Iic_timeReflect_rotate_timeReflect_le
      d r ((r + r) * lgc.sobolev_index) R hR f

/-- The two Hilbert norms actually used by every axis-pair coordinate chart
share the corrected fixed rotation coefficient, even at asymmetric splits. -/
theorem selectedBlockAxisPairHilbertNormSq_arityLinearMajorant_le
    (d n m : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS)
    {rho : Real} (hrho : 0 < rho)
    (center y y' : Fin ((n + 1 + m) * (d + 1)) → Real)
    (hcenter : ∀ i : Fin (n + 1 + m),
      rho / 2 ≤ center (finProdFinEquiv
        (i, (0 : Fin (d + 1)))))
    (P : OSIIAxisPairCompactCommonSourcePackage
      (osiiStep4SelectedBlockLeftPositiveTimeSource
        d n m hrho center y y' hcenter).1
      (osiiStep4SelectedBlockRightPositiveTimeSource
        d n m hrho center y y' hcenter).1)
    (a : osiiAxisPairIndex d) :
    P.flatTubeBranchCoordinateChartLeftNorm OS a ^ 2 ≤
        osiiArityLinearRotatedHilbertArityConstant lgc *
          ((n + 1 : Nat) : Real) ^
            ((n + 1) * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc (n + 1)).sup
            (schwartzSeminormFamily Real
              (NPointDomain d (n + 1)) Complex)
            (osiiStep4SelectedBlockLeftPositiveTimeSource
              d n m hrho center y y' hcenter).1) ^ 2 ∧
      P.flatTubeBranchCoordinateChartRightNorm OS a ^ 2 ≤
        osiiArityLinearRotatedHilbertArityConstant lgc *
          ((m + 1 : Nat) : Real) ^
            ((m + 1) * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc (m + 1)).sup
            (schwartzSeminormFamily Real
              (NPointDomain d (m + 1)) Complex)
            (osiiStep4SelectedBlockRightPositiveTimeSource
              d n m hrho center y y' hcenter).1) ^ 2 := by
  let leftPositive : SchwartzNPoint d (n + 1) :=
    (osiiStep4SelectedBlockLeftPositiveTimeSource
      d n m hrho center y y' hcenter).1
  let right : SchwartzNPoint d (m + 1) :=
    (osiiStep4SelectedBlockRightPositiveTimeSource
      d n m hrho center y y' hcenter).1
  let R := (osiiAxisPairRotationData P.T a).matrix
  let hR := (osiiAxisPairRotationData P.T a).orthogonal
  have hleft :
      tsupport
          ((osiiEuclideanRotateSchwartz R hR leftPositive.timeReflect).timeReflect :
            NPointDomain d (n + 1) → Complex) ≤
        OrderedPositiveTimeRegion d (n + 1) := by
    rw [show leftPositive.timeReflect = P.data.left by
      simpa [leftPositive] using P.left_eq.symm]
    exact SchwartzNPoint.timeReflect_tsupport_orderedPositive
      (osiiEuclideanRotateSchwartz R hR P.data.left)
      (osiiEuclideanRotateSchwartz_tsupport_orderedNegative
        R hR P.data.left (P.data.left_support a))
  have hright :
      tsupport
          (osiiEuclideanRotateSchwartz R hR right :
            NPointDomain d (m + 1) → Complex) ≤
        OrderedPositiveTimeRegion d (m + 1) := by
    rw [show right = P.data.right by
      simpa [right] using P.right_eq.symm]
    exact osiiEuclideanRotateSchwartz_tsupport_orderedPositive
      R hR P.data.right (P.data.right_support a)
  constructor
  · simpa [OSIIAxisPairCompactCommonSourcePackage.flatTubeBranchCoordinateChartLeftNorm,
      leftPositive, R, hR, P.left_eq] using
      osiiPositiveTimeSingleVector_reflectedRotated_norm_sq_arityLinearMajorant_le
        d (n + 1) OS lgc (by omega) R hR leftPositive hleft
  · simpa [OSIIAxisPairCompactCommonSourcePackage.flatTubeBranchCoordinateChartRightNorm,
      right, R, hR, P.right_eq] using
      osiiPositiveTimeSingleVector_rotated_norm_sq_arityLinearMajorant_le
        d (m + 1) OS lgc (by omega) R hR right hright

/-- The actual rotated axis-pair chart vectors have one corrected E0' majorant
over every split, source slice, packet slope, and active coordinate. -/
theorem exists_selectedBlockAxisPairHilbertNormSq_fixedArityMajorant
    (d : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS) :
    ∃ A : Real, 0 ≤ A ∧ ∃ beta : Nat,
      ∀ (n m : Nat) {rho : Real}
        (hrho : 0 < rho) (_ : rho ≤ 16)
        (center y y' : Fin ((n + 1 + m) * (d + 1)) → Real)
        (hcenter : ∀ i : Fin (n + 1 + m),
          rho / 2 ≤ center (finProdFinEquiv
            (i, (0 : Fin (d + 1)))))
        (P : OSIIAxisPairCompactCommonSourcePackage
          (osiiStep4SelectedBlockLeftPositiveTimeSource
            d n m hrho center y y' hcenter).1
          (osiiStep4SelectedBlockRightPositiveTimeSource
            d n m hrho center y y' hcenter).1)
        (a : osiiAxisPairIndex d),
        let B : Real :=
          A * ((n + 1 + m : Nat) : Real) ^
              ((n + 1 + m) * beta) *
            (16 / rho) ^
              (2 * (n + 1 + m) *
                (3 * (d + 1) + 4 * lgc.sobolev_index)) *
            (1 + ‖center‖) ^
              (8 * (n + 1 + m) * lgc.sobolev_index)
        P.flatTubeBranchCoordinateChartLeftNorm OS a ^ 2 ≤ B ∧
          P.flatTubeBranchCoordinateChartRightNorm OS a ^ 2 ≤ B := by
  obtain ⟨sourceBase, hsourceBase, hsource⟩ :=
    exists_radialEndpointFullSource_fixedArityMajorant
      d lgc.sobolev_index
  let H : Real := osiiArityLinearRotatedHilbertArityConstant lgc
  let growth : Nat := 12 * lgc.sobolev_index + 6
  let exponential : Real := sourceBase ^ 2
  let A : Real := H * max exponential 1
  let beta : Nat :=
    osiiArityLinearRotatedHilbertArityRate lgc +
      2 * growth + Nat.ceil (max exponential 1)
  have hH : 0 ≤ H := by
    dsimp [H, osiiArityLinearRotatedHilbertArityConstant]
    exact mul_nonneg (osiiArityLinearHilbertArityConstant_nonneg lgc)
      (by positivity)
  have hA : 0 ≤ A := by
    dsimp [A]
    positivity
  refine ⟨A, hA, beta, ?_⟩
  intro n m rho hrho hrho_le center y y' hcenter P a
  let K : Nat := n + 1 + m
  let X : Real := 16 / rho
  let Y : Real := 1 + ‖center‖
  let degree : Nat := 3 * (d + 1) + 4 * lgc.sobolev_index
  let B : Real :=
    A * (K : Real) ^ (K * beta) *
      X ^ (2 * K * degree) *
      Y ^ (8 * K * lgc.sobolev_index)
  have hX : 1 ≤ X := by
    dsimp [X]
    exact (le_div_iff₀ hrho).2 (by simpa using hrho_le)
  have hY : 1 ≤ Y := by
    dsimp [Y]
    linarith [norm_nonneg center]
  have hexponential : 0 ≤ exponential := by
    dsimp [exponential]
    positivity
  have hradial (j : Nat) (hj : j + 1 ≤ K)
      (endpointCenter endpointImag : SpacetimeDim d)
      (tail v v' : Fin (j * (d + 1)) → Real)
      (hendpointNorm : ‖endpointCenter‖ ≤ ‖center‖)
      (htailNorm : ‖tail‖ ≤ ‖center‖)
      (u : Real)
      (hvector :
        u ^ 2 ≤ H * ((j + 1 : Nat) : Real) ^
            ((j + 1) * osiiArityLinearRotatedHilbertArityRate lgc) *
          ((osiiArityLinearHilbertSeminorms lgc (j + 1)).sup
            (schwartzSeminormFamily Real
              (NPointDomain d (j + 1)) Complex)
            (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
              d j hrho endpointCenter endpointImag tail v v')) ^ 2) :
      u ^ 2 ≤ B := by
    let r : Nat := j + 1
    let R : Real := r
    let L : Nat := r * (2 * lgc.sobolev_index)
    let f : SchwartzNPoint d r :=
      osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
        d j hrho endpointCenter endpointImag tail v v'
    let Q : Real :=
      (osiiArityLinearHilbertSeminorms lgc r).sup
        (schwartzSeminormFamily Real (NPointDomain d r) Complex) f
    have hr : 0 < r := by
      dsimp [r]
      omega
    have hQ : 0 ≤ Q := apply_nonneg _ _
    have hindex : (r + r) * lgc.sobolev_index = L := by
      dsimp [L]
      ring
    have hintercept :
        2 * (d + 1) + 4 * lgc.sobolev_index ≤ degree := by
      dsimp [degree]
      omega
    have hscale :
        j * degree + (2 * (d + 1) + 4 * lgc.sobolev_index) ≤
          r * degree := by
      calc
        j * degree + (2 * (d + 1) + 4 * lgc.sobolev_index) ≤
          j * degree + degree := Nat.add_le_add_left hintercept _
        _ = r * degree := by
          dsimp [r]
          ring
    have hsource' :=
      hsource j hrho hrho_le endpointCenter endpointImag tail v v'
    have hQbound :
        Q ≤ sourceBase ^ r * R ^ (growth * r) *
          X ^ (r * degree) * Y ^ (2 * L) := by
      calc
        Q ≤ sourceBase ^ r * R ^ (growth * r) *
            X ^ (j * degree +
              (2 * (d + 1) + 4 * lgc.sobolev_index)) *
            (1 + ‖endpointCenter‖) ^ L *
            (1 + ‖tail‖) ^ L := by
              simpa [Q, f, R, r, growth, X, degree, L,
                osiiArityLinearHilbertSeminorms, hindex] using hsource'
        _ ≤ sourceBase ^ r * R ^ (growth * r) *
            X ^ (r * degree) * Y ^ L * Y ^ L := by
              gcongr
              · simpa [Y] using add_le_add_left hendpointNorm 1
              · simpa [Y] using add_le_add_left htailNorm 1
        _ = sourceBase ^ r * R ^ (growth * r) *
            X ^ (r * degree) * Y ^ (2 * L) := by
              rw [show 2 * L = L + L by omega, pow_add]
              ring
    have habsorb :
        exponential ^ r ≤
          max exponential 1 *
            R ^ (r * Nat.ceil (max exponential 1)) := by
      simpa [R] using
        nonneg_pow_le_max_mul_arityPow exponential hexponential r hr
    have hcoefficient :
        H * R ^ (r * osiiArityLinearRotatedHilbertArityRate lgc) *
            (sourceBase ^ r * R ^ (growth * r)) ^ 2 ≤
          A * R ^ (r * beta) := by
      calc
        H * R ^ (r * osiiArityLinearRotatedHilbertArityRate lgc) *
            (sourceBase ^ r * R ^ (growth * r)) ^ 2 =
          H * exponential ^ r *
            R ^ (r * (osiiArityLinearRotatedHilbertArityRate lgc +
              2 * growth)) := by
                dsimp [exponential]
                simp only [mul_pow, ← pow_mul]
                ring
        _ ≤ H *
            (max exponential 1 *
              R ^ (r * Nat.ceil (max exponential 1))) *
            R ^ (r * (osiiArityLinearRotatedHilbertArityRate lgc +
              2 * growth)) := by
                gcongr
        _ = A * R ^ (r * beta) := by
          dsimp [A, beta]
          rw [Nat.mul_add, pow_add]
          ring
    have hpoint : R ^ (r * beta) ≤ (K : Real) ^ (K * beta) := by
      simpa [R] using arityPow_le_arityPow_of_le r K beta hr hj
    have hscale' : 2 * r * degree ≤ 2 * K * degree := by
      exact Nat.mul_le_mul_right degree (Nat.mul_le_mul_left 2 hj)
    have hcenterDegree : 4 * L ≤ 8 * K * lgc.sobolev_index := by
      calc
        4 * L = 8 * r * lgc.sobolev_index := by
          dsimp [L]
          ring
        _ ≤ 8 * K * lgc.sobolev_index := by
          exact Nat.mul_le_mul_right lgc.sobolev_index
            (Nat.mul_le_mul_left 8 hj)
    have hvector' :
        u ^ 2 ≤ H * R ^
          (r * osiiArityLinearRotatedHilbertArityRate lgc) * Q ^ 2 := by
      simpa [Q, f, R, r] using hvector
    calc
      u ^ 2 ≤ H * R ^
          (r * osiiArityLinearRotatedHilbertArityRate lgc) * Q ^ 2 :=
        hvector'
      _ ≤ H * R ^
          (r * osiiArityLinearRotatedHilbertArityRate lgc) *
          (sourceBase ^ r * R ^ (growth * r) *
            X ^ (r * degree) * Y ^ (2 * L)) ^ 2 := by
            gcongr
      _ = (H * R ^
            (r * osiiArityLinearRotatedHilbertArityRate lgc) *
            (sourceBase ^ r * R ^ (growth * r)) ^ 2) *
          X ^ (2 * r * degree) * Y ^ (4 * L) := by
            simp only [mul_pow, ← pow_mul]
            ring
      _ ≤ A * R ^ (r * beta) *
          X ^ (2 * r * degree) * Y ^ (4 * L) := by
            gcongr
      _ ≤ A * (K : Real) ^ (K * beta) *
          X ^ (2 * K * degree) *
          Y ^ (8 * K * lgc.sobolev_index) := by
            gcongr
  have hchart := selectedBlockAxisPairHilbertNormSq_arityLinearMajorant_le
    d n m OS lgc hrho center y y' hcenter P a
  change
    P.flatTubeBranchCoordinateChartLeftNorm OS a ^ 2 ≤ B ∧
      P.flatTubeBranchCoordinateChartRightNorm OS a ^ 2 ≤ B
  constructor
  · apply hradial n (by dsimp [K]; omega)
      (osiiStep4SelectedBlockLeftEndpointCenter d n m center)
      (osiiStep4SelectedBlockLeftEndpointImag d n m y y')
      (osiiStep4ParityReversedBeforeRealBlocks d n m center)
      (osiiStep4ParityReversedBeforeRealBlocks d n m y)
      (osiiStep4ParityReversedBeforeRealBlocks d n m y')
      (norm_selectedBlockLeftEndpointCenter_le d n m center)
      (norm_parityReversedBefore_le d n m center)
      (P.flatTubeBranchCoordinateChartLeftNorm OS a)
    simpa [H, osiiStep4SelectedBlockLeftPositiveTimeSource,
      osiiStep4RadialEndpointPositiveTimeSource] using hchart.1
  · apply hradial m (by dsimp [K]; omega)
      (osiiStep4SelectedBlockRightEndpointCenter d n m center)
      (osiiStep4SelectedBlockRightEndpointImag d n m y')
      (osiiStep4AfterRealBlocks n m (d + 1) center)
      (osiiStep4AfterRealBlocks n m (d + 1) y)
      (osiiStep4AfterRealBlocks n m (d + 1) y')
      (norm_selectedBlockRightEndpointCenter_le d n m center)
      (norm_afterBlocks_le n m (d + 1) center)
      (P.flatTubeBranchCoordinateChartRightNorm OS a)
    simpa [H, osiiStep4SelectedBlockRightPositiveTimeSource,
      osiiStep4RadialEndpointPositiveTimeSource] using hchart.2

/-- The exact coordinate-chart constant consumed by the existing axis-pair
continuation inherits one fixed corrected E0' coefficient at every arity. -/
theorem exists_selectedBlockAxisPairCoordinateChartBound_fixedArityMajorant
    (d : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSArityLinearGrowthCondition d OS) :
    ∃ A : Real, 0 ≤ A ∧ ∃ beta : Nat,
      ∀ (n m : Nat) {rho : Real}
        (hrho : 0 < rho) (_ : rho ≤ 16)
        (center y y' : Fin ((n + 1 + m) * (d + 1)) → Real)
        (hcenter : ∀ i : Fin (n + 1 + m),
          rho / 2 ≤ center (finProdFinEquiv
            (i, (0 : Fin (d + 1)))))
        (P : OSIIAxisPairCompactCommonSourcePackage
          (osiiStep4SelectedBlockLeftPositiveTimeSource
            d n m hrho center y y' hcenter).1
          (osiiStep4SelectedBlockRightPositiveTimeSource
            d n m hrho center y y' hcenter).1)
        (a : osiiAxisPairIndex d),
        P.flatTubeBranchCoordinateChartBound OS a ≤
          A * ((n + 1 + m : Nat) : Real) ^
              ((n + 1 + m) * beta) *
            (16 / rho) ^
              (2 * (n + 1 + m) *
                (3 * (d + 1) + 4 * lgc.sobolev_index)) *
            (1 + ‖center‖) ^
              (8 * (n + 1 + m) * lgc.sobolev_index) := by
  obtain ⟨A, hA, beta, hbound⟩ :=
    exists_selectedBlockAxisPairHilbertNormSq_fixedArityMajorant d OS lgc
  refine ⟨2 * A, by positivity, beta, ?_⟩
  intro n m rho hrho hrho_le center y y' hcenter P a
  let B : Real :=
    A * ((n + 1 + m : Nat) : Real) ^
        ((n + 1 + m) * beta) *
      (16 / rho) ^
        (2 * (n + 1 + m) *
          (3 * (d + 1) + 4 * lgc.sobolev_index)) *
      (1 + ‖center‖) ^
        (8 * (n + 1 + m) * lgc.sobolev_index)
  have hboth := hbound n m hrho hrho_le center y y' hcenter P a
  calc
    P.flatTubeBranchCoordinateChartBound OS a ≤
        P.flatTubeBranchCoordinateChartLeftNorm OS a ^ 2 +
          P.flatTubeBranchCoordinateChartRightNorm OS a ^ 2 :=
      P.flatTubeBranchCoordinateChartBound_le_normSq_add OS a
    _ ≤ B + B := add_le_add hboth.1 hboth.2
    _ = (2 * A) * ((n + 1 + m : Nat) : Real) ^
          ((n + 1 + m) * beta) *
        (16 / rho) ^
          (2 * (n + 1 + m) *
            (3 * (d + 1) + 4 * lgc.sobolev_index)) *
        (1 + ‖center‖) ^
          (8 * (n + 1 + m) * lgc.sobolev_index) := by
      dsimp [B]
      ring

theorem osiiE0PrimeHilbertNormSqFactor_nonneg
    {d : Nat} [NeZero d]
    {OS : OsterwalderSchraderAxioms d}
    (lgc : OSFixedOrderGrowthCondition d OS)
    (r : Nat) :
    0 <= osiiE0PrimeHilbertNormSqFactor lgc r := by
  unfold osiiE0PrimeHilbertNormSqFactor osiiE0PrimeHilbertTensorFactor
  exact mul_nonneg
    (mul_nonneg
      (mul_nonneg lgc.alpha_pos.le
        (pow_nonneg lgc.beta_pos.le _))
      (Real.rpow_nonneg (by positivity) _))
    (by positivity)

/-- E0' controls every positive-time one-vector norm square by the same
finite seminorm indices and its exact arity coefficient. -/
theorem osiiPositiveTimeSingleVector_norm_sq_e0PrimeSeminorms_le
    (d r : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSFixedOrderGrowthCondition d OS) :
    ∀ (g : SchwartzNPoint d r)
        (hg : tsupport (g : NPointDomain d r -> Complex) <=
          OrderedPositiveTimeRegion d r),
      ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 <=
        osiiE0PrimeHilbertNormSqFactor lgc r *
          ((osiiE0PrimeHilbertSeminorms lgc).sup
            (schwartzSeminormFamily Real
              (NPointDomain d r) Complex) g) ^ 2 := by
  let s := lgc.sobolev_index
  let t := osiiE0PrimeHilbertSeminorms lgc
  let P : Real :=
    lgc.alpha * lgc.beta ^ (r + r) *
      ((r + r).factorial : Real) ^ lgc.gamma
  let H : Real :=
    2 ^ s *
      ∑ i ∈ Finset.range (s + 1),
        (s.choose i : Real) * (1 + 1)
  have hP : 0 <= P := by
    dsimp [P]
    exact mul_nonneg
      (mul_nonneg lgc.alpha_pos.le
        (pow_nonneg lgc.beta_pos.le _))
      (Real.rpow_nonneg (by positivity) _)
  have hH : 0 <= H := by
    dsimp [H]
    positivity
  intro g hg
  let Q : Real :=
    t.sup (schwartzSeminormFamily Real
      (NPointDomain d r) Complex) g
  have hos := osiiPositiveTimeSingleVectorCLM_norm_sq_le_finsetSup
    OS lgc g hg
  calc
    ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 <=
      P *
        (2 ^ s *
          ∑ i ∈ Finset.range (s + 1),
            (s.choose i : Real) * (Q * Q + Q * Q)) := by
      simpa [P, s, t, osiiE0PrimeHilbertSeminorms, Q] using hos
    _ = P * H * Q ^ 2 := by
      have hsum :
          (∑ i ∈ Finset.range (s + 1),
              (s.choose i : Real) * (Q * Q + Q * Q)) =
            (∑ i ∈ Finset.range (s + 1),
              (s.choose i : Real) * (1 + 1)) * Q ^ 2 := by
        rw [Finset.sum_mul]
        apply Finset.sum_congr rfl
        intro i hi
        simp only [pow_two]
        ring
      rw [hsum]
      dsimp [H]
      ring
    _ = osiiE0PrimeHilbertNormSqFactor lgc r * Q ^ 2 := by
      rfl

/-- Existential wrapper for callers that do not need to inspect the exact
E0' arity coefficient. -/
theorem exists_osiiPositiveTimeSingleVector_norm_sq_e0PrimeSeminorms_bound
    (d r : Nat) [NeZero d]
    (OS : OsterwalderSchraderAxioms d)
    (lgc : OSFixedOrderGrowthCondition d OS) :
    ∃ K : Real, 0 <= K ∧
      ∀ (g : SchwartzNPoint d r)
          (hg : tsupport (g : NPointDomain d r -> Complex) <=
            OrderedPositiveTimeRegion d r),
        ‖osiiPositiveTimeSingleVectorCLM OS r ⟨g, hg⟩‖ ^ 2 <=
          K *
            ((osiiE0PrimeHilbertSeminorms lgc).sup
              (schwartzSeminormFamily Real
                (NPointDomain d r) Complex) g) ^ 2 := by
  exact ⟨osiiE0PrimeHilbertNormSqFactor lgc r,
    osiiE0PrimeHilbertNormSqFactor_nonneg lgc r,
    osiiPositiveTimeSingleVector_norm_sq_e0PrimeSeminorms_le d r OS lgc⟩

/-- Quantitative radial-source data with all degrees selected before arity.
The numerical coefficient is allowed to depend on arity, as in OS II
equation `(6.20)`. -/
structure OSIIUniformRadialEndpointSourceDegreeData
    (d : Nat) [NeZero d]
    (t : Finset (Nat × Nat)) where
  scaleOffset : Nat
  endpointDegree : Nat
  tailDegree : Nat
  bound :
    ∀ k : Nat, ∃ C : Real, 0 <= C ∧
      ∀ {rho : Real} (hrho : 0 < rho), rho <= 16 ->
        ∀ (endpointCenter endpointImag : SpacetimeDim d),
          endpointImag ∈ Metric.closedBall 0 (rho / 8) ->
            ∀ (center : Fin (k * (d + 1)) -> Real),
              ∀ p ∈ osiiStep4PartialConvolutionClosedImaginaryBox
                  (d + 1) k rho,
                t.sup (schwartzSeminormFamily Real
                    (NPointDomain d (k + 1)) Complex)
                    (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
                      d k hrho endpointCenter endpointImag
                        center p.1 p.2) <=
                  C * (16 / rho) ^
                      (3 * (d + 1) * k + scaleOffset) *
                    (1 + ‖endpointCenter‖) ^ endpointDegree *
                    (1 + ‖center‖) ^ tailDegree

set_option maxHeartbeats 800000 in
/-- The selected left source retains the uniform radial degrees. Its only
arity dependence is the explicit linear term `3 * (d + 1) * n`. -/
theorem OSIIUniformRadialEndpointSourceDegreeData.exists_selectedBlockLeft_bound
    {d : Nat} [NeZero d]
    {t : Finset (Nat × Nat)}
    (D : OSIIUniformRadialEndpointSourceDegreeData d t)
    (n m : Nat) :
    ∃ C : Real, 0 <= C ∧
      ∀ {rho : Real} (hrho : 0 < rho), rho <= 16 ->
        ∀ (center : Fin ((n + 1 + m) * (d + 1)) -> Real),
          ∀ hcenter : ∀ i : Fin (n + 1 + m),
            rho / 2 <= center (finProdFinEquiv (i, (0 : Fin (d + 1)))),
              ∀ p ∈ osiiStep4PartialConvolutionClosedImaginaryBox
                  (d + 1) (n + 1 + m) rho,
                t.sup (schwartzSeminormFamily Real
                    (NPointDomain d (n + 1)) Complex)
                    (osiiStep4SelectedBlockLeftPositiveTimeSource
                      d n m hrho center p.1 p.2 hcenter).1 <=
                  C * (16 / rho) ^
                      (3 * (d + 1) * n + D.scaleOffset) *
                    (1 + norm center) ^
                      (D.endpointDegree + D.tailDegree) := by
  obtain ⟨C, hC, hbound⟩ := D.bound n
  refine ⟨C, hC, ?_⟩
  intro rho hrho hrho_le center hcenter p hp
  let endpointCenter :=
    osiiStep4SelectedBlockLeftEndpointCenter d n m center
  let endpointImag :=
    osiiStep4SelectedBlockLeftEndpointImag d n m p.1 p.2
  let centerL := osiiStep4ParityReversedBeforeRealBlocks d n m center
  let yL := osiiStep4ParityReversedBeforeRealBlocks d n m p.1
  let yL' := osiiStep4ParityReversedBeforeRealBlocks d n m p.2
  have hy : norm p.1 <= rho / 4 := by
    simpa [Metric.mem_closedBall, dist_zero_right] using hp.1
  have hy' : norm p.2 <= rho / 8 := by
    simpa [Metric.mem_closedBall, dist_zero_right] using hp.2
  by_cases hEndpointImag : norm endpointImag <= rho / 8
  · have hEndpointImagMem :
        endpointImag ∈ Metric.closedBall 0 (rho / 8) := by
      simpa [Metric.mem_closedBall, dist_zero_right] using hEndpointImag
    have hpL : (yL, yL') ∈
        osiiStep4PartialConvolutionClosedImaginaryBox (d + 1) n rho := by
      constructor
      · rw [Metric.mem_closedBall, dist_zero_right]
        exact (norm_parityReversedBefore_le d n m p.1).trans hy
      · rw [Metric.mem_closedBall, dist_zero_right]
        exact (norm_parityReversedBefore_le d n m p.2).trans hy'
    have hradial := hbound hrho hrho_le endpointCenter endpointImag
      hEndpointImagMem centerL (yL, yL') hpL
    have hEndpointCenterNorm : norm endpointCenter <= norm center := by
      simpa [endpointCenter] using
        norm_selectedBlockLeftEndpointCenter_le d n m center
    have hcenterLNorm : norm centerL <= norm center := by
      simpa [centerL] using norm_parityReversedBefore_le d n m center
    have hbase : 0 <= 1 + norm center := by positivity
    change t.sup (schwartzSeminormFamily Real
        (NPointDomain d (n + 1)) Complex)
        (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
          d n hrho endpointCenter endpointImag centerL yL yL') <= _
    calc
      t.sup (schwartzSeminormFamily Real
          (NPointDomain d (n + 1)) Complex)
          (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
            d n hrho endpointCenter endpointImag centerL yL yL') <=
        C * (16 / rho) ^
            (3 * (d + 1) * n + D.scaleOffset) *
          (1 + norm endpointCenter) ^ D.endpointDegree *
          (1 + norm centerL) ^ D.tailDegree := hradial
      _ <= C * (16 / rho) ^
            (3 * (d + 1) * n + D.scaleOffset) *
          (1 + norm center) ^ D.endpointDegree *
          (1 + norm center) ^ D.tailDegree := by
        gcongr
      _ = C * (16 / rho) ^
            (3 * (d + 1) * n + D.scaleOffset) *
          (1 + norm center) ^
            (D.endpointDegree + D.tailDegree) := by
        rw [pow_add]
        ring
  · have hEndpointImag' : rho / 8 < norm endpointImag :=
      lt_of_not_ge hEndpointImag
    have hsourceZero :
        osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
          d n hrho endpointCenter endpointImag centerL yL yL' = 0 :=
      radialEndpointSource_eq_zero_of_imag_norm_gt
        d n hrho endpointCenter endpointImag centerL yL yL' hEndpointImag'
    change t.sup (schwartzSeminormFamily Real
        (NPointDomain d (n + 1)) Complex)
        (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
          d n hrho endpointCenter endpointImag centerL yL yL') <= _
    rw [hsourceZero]
    simp
    positivity

set_option maxHeartbeats 800000 in
/-- The selected right source retains the same uniform radial degrees, with
the explicit arity term determined by the right block size `m`. -/
theorem OSIIUniformRadialEndpointSourceDegreeData.exists_selectedBlockRight_bound
    {d : Nat} [NeZero d]
    {t : Finset (Nat × Nat)}
    (D : OSIIUniformRadialEndpointSourceDegreeData d t)
    (n m : Nat) :
    ∃ C : Real, 0 <= C ∧
      ∀ {rho : Real} (hrho : 0 < rho), rho <= 16 ->
        ∀ (center : Fin ((n + 1 + m) * (d + 1)) -> Real),
          ∀ hcenter : ∀ i : Fin (n + 1 + m),
            rho / 2 <= center (finProdFinEquiv (i, (0 : Fin (d + 1)))),
              ∀ p ∈ osiiStep4PartialConvolutionClosedImaginaryBox
                  (d + 1) (n + 1 + m) rho,
                t.sup (schwartzSeminormFamily Real
                    (NPointDomain d (m + 1)) Complex)
                    (osiiStep4SelectedBlockRightPositiveTimeSource
                      d n m hrho center p.1 p.2 hcenter).1 <=
                  C * (16 / rho) ^
                      (3 * (d + 1) * m + D.scaleOffset) *
                    (1 + norm center) ^
                      (D.endpointDegree + D.tailDegree) := by
  obtain ⟨C, hC, hbound⟩ := D.bound m
  refine ⟨C, hC, ?_⟩
  intro rho hrho hrho_le center hcenter p hp
  let endpointCenter :=
    osiiStep4SelectedBlockRightEndpointCenter d n m center
  let endpointImag :=
    osiiStep4SelectedBlockRightEndpointImag d n m p.2
  let centerR := osiiStep4AfterRealBlocks n m (d + 1) center
  let yR := osiiStep4AfterRealBlocks n m (d + 1) p.1
  let yR' := osiiStep4AfterRealBlocks n m (d + 1) p.2
  have hy : norm p.1 <= rho / 4 := by
    simpa [Metric.mem_closedBall, dist_zero_right] using hp.1
  have hy' : norm p.2 <= rho / 8 := by
    simpa [Metric.mem_closedBall, dist_zero_right] using hp.2
  have hpR : (yR, yR') ∈
      osiiStep4PartialConvolutionClosedImaginaryBox (d + 1) m rho := by
    constructor
    · rw [Metric.mem_closedBall, dist_zero_right]
      exact (norm_afterBlocks_le n m (d + 1) p.1).trans hy
    · rw [Metric.mem_closedBall, dist_zero_right]
      exact (norm_afterBlocks_le n m (d + 1) p.2).trans hy'
  have hEndpointImag : norm endpointImag <= rho / 8 := by
    apply le_trans _ hy'
    rw [pi_norm_le_iff_of_nonneg (norm_nonneg p.2)]
    intro mu
    simpa [endpointImag, osiiStep4SelectedBlockRightEndpointImag,
      osiiStep4SelectedRealBlock] using
      (norm_le_pi_norm p.2
        (finProdFinEquiv (osiiStep4SelectedBlockIndex n m, mu)))
  have hEndpointImagMem :
      endpointImag ∈ Metric.closedBall 0 (rho / 8) := by
    simpa [Metric.mem_closedBall, dist_zero_right] using hEndpointImag
  have hradial := hbound hrho hrho_le endpointCenter endpointImag
    hEndpointImagMem centerR (yR, yR') hpR
  have hEndpointCenterNorm : norm endpointCenter <= norm center := by
    simpa [endpointCenter] using
      norm_selectedBlockRightEndpointCenter_le d n m center
  have hcenterRNorm : norm centerR <= norm center := by
    simpa [centerR] using norm_afterBlocks_le n m (d + 1) center
  change t.sup (schwartzSeminormFamily Real
      (NPointDomain d (m + 1)) Complex)
      (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
        d m hrho endpointCenter endpointImag centerR yR yR') <= _
  calc
    t.sup (schwartzSeminormFamily Real
        (NPointDomain d (m + 1)) Complex)
        (osiiStep4RadialEndpointLiftedCenteredPartialConvolutionKernelFullSource
          d m hrho endpointCenter endpointImag centerR yR yR') <=
      C * (16 / rho) ^
          (3 * (d + 1) * m + D.scaleOffset) *
        (1 + norm endpointCenter) ^ D.endpointDegree *
        (1 + norm centerR) ^ D.tailDegree := hradial
    _ <= C * (16 / rho) ^
          (3 * (d + 1) * m + D.scaleOffset) *
        (1 + norm center) ^ D.endpointDegree *
        (1 + norm center) ^ D.tailDegree := by
      gcongr
    _ = C * (16 / rho) ^
          (3 * (d + 1) * m + D.scaleOffset) *
        (1 + norm center) ^
          (D.endpointDegree + D.tailDegree) := by
      rw [pow_add]
      ring

end OSReconstruction
